### PR TITLE
run local finalization testnets with Geth

### PR DESCRIPTION
**Pull request by etan-status**
Enable full 🐼 testing in local finalization testnets.

### CODE REVIEW

**Comment by etan-status** [comment]
image

**Comment by etan-status** [comment]
Geth doesn't provide binaries for ARM macOS, so restricted to Intel for now.

**Comment by etan-status** [comment]
Checked Jenkins CI, and confirmed that Geth is being run on Linux and macOS-Intel.
On macOS-AS, there are no official Geth binaries, so running without Geth there.

**Comment by arnetheduck** [comment]
nice!

**Pull request merged**
