### PR TITLE
Revert "correctly align genesis size"

### PR DESCRIPTION
**Pull request by tersec**
Reverts status-im/nimbus-eth2#5244

breaks `unstable`

### CODE REVIEW

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/actions/runs/5763732163/job/15626176737

https://github.com/status-im/nimbus-eth2/actions/runs/5763732163/job/15626176931

ostensibly, a bunch of UBSAN-linking-related errors, which is a bit odd.

```
...
abi/sqlite3_abi/sqlite3.c:101089: undefined reference to `__ubsan_handle_pointer_overflow'
/usr/bin/ld: /home/runner/work/nimbus-eth2/nimbus-eth2/vendor/nim-sqlite3-abi/sqlite3_abi/sqlite3.c:101089: undefined reference to `__ubsan_handle_type_mismatch_v1'
/usr/bin/ld: /home/runner/work/nimbus-eth2/nimbus-eth2/vendor/nim-sqlite3-abi/sqlite3_abi/sqlite3.c:101086: undefined reference to `__ubsan_handle_type_mismatch_v1'
/usr/bin/ld: /home/runner/work/nimbus-eth2/nimbus-eth2/vendor/nim-sqlite3-abi/sqlite3_abi/sqlite3.c:101086: undefined reference to `__ubsan_handle_type_mismatch_v1'
/usr/bin/ld: /home/runner/work/nimbus-eth2/nimbus-eth2/vendor/nim-sqlite3-abi/sqlite3_abi/sqlite3.c:101086: undefined reference to `__ubsan_handle_type_mismatch_v1'
/usr/bin/ld: /home/runner/work/nimbus-eth2/nimbus-eth2/vendor/nim-sqlite3-abi/sqlite3_abi/sqlite3.c:101086: undefined reference to `__ubsan_handle_type_mismatch_v1'
/usr/bin/ld: build/libnimbus_lc.a(@m..@s..@svendor@sn
This step has been truncated due to its large size. Download the full logs from the
menu once the workflow run has completed. 
```

**Comment by etan-status** [comment]
the ubsan errors randomly pop up depending on commit hash modulo

**Comment by etan-status** [comment]
```
          # Stack usage test and UBSAN on recent enough gcc:
          if [[ '${{ runner.os }}' == 'Linux' && '${{ matrix.target.cpu }}' == 'amd64' ]]; then
            if [[ '${{ github.sha }}' =~ ^7 ]]; then
              export NIMFLAGS="${NIMFLAGS} -d:limitStackUsage --passC:-fsanitize=undefined --passL:-fsanitize=undefined"
            else
              export NIMFLAGS="${NIMFLAGS} -d:limitStackUsage"
            fi
            echo "NIMFLAGS=${NIMFLAGS}" >> $GITHUB_ENV
          fi
```

**Comment by tersec** [comment]
popped up with a commit hash beginning with `1` in https://github.com/status-im/nimbus-eth2/pull/5251

```
Commit 14aa7b1efd28d077b92bd971924f8dbff4001a9e (HEAD -> YmY, origin/YmY)
Author: tersec <tersec@users.noreply.github.com>
Date:   Fri Aug 4 18:16:21 2023 +0000

    remove more Bellatrix-only Builder API support infrastructure
```

**Comment by etan-status** [comment]
github tests don't run on your commit, but first creates a hidden merge from base branch into the pr. that one is the one being tested.

**Comment by tersec** [comment]
Also, if the UBSAN is failing this way (and, yes, checked the previous `7`-commithash-commits, and the recent ones failed in the same way, apparently: 

That said,
- https://github.com/status-im/nimbus-eth2/commit/7028cc45f5c3bc0f7948061e8bbb8b05ad3f324b
- https://github.com/status-im/nimbus-eth2/commit/7b0e3b1c04a45ec6f0dc92531ee2cd59fe278f34 (Jun 29)
- https://github.com/status-im/nimbus-eth2/commit/7fc99ff040a19bc0e85e36947e33e79dd6420761 (Jul 10)
- https://github.com/status-im/nimbus-eth2/commit/74bb4b1411590ed660c1dd20147268dc89630f3f (Jul 12)
- https://github.com/status-im/nimbus-eth2/commit/703eead2e6d6e3615ac09b168cc1179e7c1664ff (Jul 13)

all ran UBSAN in CI fine, so it was some breakage between then and now. It's not just been this "random" thing for months. It's been 2-3 weeks.

https://github.com/status-im/nimbus-eth2/commit/722b7f6f6b658e55bc0c2b59d8b56a0845c7d36a (Jul 19) is the first `7`-commit with this issue.

So, either environmental change, or one of
- https://github.com/status-im/nimbus-eth2/commit/f1963bf599f26aa98b26bde533e1df87ac9655f6
- https://github.com/status-im/nimbus-eth2/commit/565edfa35131fab36c3accc3106359181ac80d4d
- https://github.com/status-im/nimbus-eth2/commit/2efc44a8ab1ad8457a56a656608ba72515a96851
- https://github.com/status-im/nimbus-eth2/commit/92da61ce8818e7a67c679226a0540841b6fbbd29
- https://github.com/status-im/nimbus-eth2/commit/3a818ecb93344d71fb63d4f52dc4da2a2bfe96bc
- https://github.com/status-im/nimbus-eth2/commit/f98c33ad03d44b005f6f6fb76502b03599d66d2b
- https://github.com/status-im/nimbus-eth2/commit/dd35d2d3094c277984beb4d6672a458578beb20d
- https://github.com/status-im/nimbus-eth2/commit/b3b5238434304b10b57b49a30ce3aebb5a4e5922
- https://github.com/status-im/nimbus-eth2/commit/346d05a95dbb622a82021c97b5cd407b15c9c867
- https://github.com/status-im/nimbus-eth2/commit/971b4483c5db2e5dec953709a2191f656fdbca2d
- https://github.com/status-im/nimbus-eth2/commit/722b7f6f6b658e55bc0c2b59d8b56a0845c7d36a

at least proximately triggered this (might have uncovered/interacted with another pre-existing issue, etc).

So, agree that the initial revert was hasty, will undo it.

The UBSAN thing still should be either
- removed from CI entirely (not great, CI is demonstrating it won't work, and being literally unable to run UBSAN on Nimbus is not good)
- increased in frequency, despite taking longer to build. Maybe add another commithash, or use another mechanism. But it can't be this midpoint of rarity where it's possible to kind of dismiss as "the ubsan errors randomly pop up depending on commit hash modulo" and move on.

Initially, they were every commit, until there was an observation that, yes, it made the GitHub Actions Linux build take 2+ hours.

But better to find out this way than months later that using UBSAN is relatively newly broken.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/5257

**Pull request merged**
