### PR TITLE
libp2p revert

### PR DESCRIPTION
**Pull request by tersec**
Effectively reverts the libp2p bump from https://github.com/status-im/nim-beacon-chain/pull/1289

See if this finalizes in Jenkins CI

### CODE REVIEW

**Comment by tersec** [comment]
going to see if this triggers another CI run, to test more

**Comment by arnetheduck** [comment]
bah, ideally one would be able to bisect the exact libp2p commit where it died

**Comment by arnetheduck** [comment]
testing a few commits in #1331

**Comment by tersec** [comment]
> bah, ideally one would be able to bisect the exact libp2p commit where it died

that's what I've been doing today

**Comment by tersec** [comment]
we'll know within an hour; started with 32 commits, now down to:
```
4e12d0d97ad1b4fb6e04320e87f2a739a0cc557d # fails x2
f9e0a1f069c836195e66dfb551631f9e2be43c21
9b8b159abb34e5e2f894a602ddb50e9efb12f1fb # in process
4bcb567d47d80cfbd2b5ff5b5642945913a45083
4698f41a9111227e8572ddd029849f64d5b67ada # fails x2
fec507e7559d7f26b750cffa29a373e03fd42ecd # in process
a52763cc6dfa92b5a6ad374ba7b802f57eed8ac7 # in process
775cab414a68843c93c75e357f69cb1c04b32edd # works x2
d522537b19a532bc4af94fcd146f779c1f23bad0 # works x2
```

**Comment by tersec** [comment]
Either `fec507e7559d7f26b750cffa29a373e03fd42ecd` or `a52763cc6dfa92b5a6ad374ba7b802f57eed8ac7` is the culprit. Will know more shortly.

**Comment by tersec** [comment]
It's https://github.com/status-im/nim-libp2p/commit/a52763cc6dfa92b5a6ad374ba7b802f57eed8ac7

That is, the commit before, `775cab414a68843c93c75e357f69cb1c04b32edd`, works: https://github.com/status-im/nim-beacon-chain/pull/1332

The commit after, `a52763cc6dfa92b5a6ad374ba7b802f57eed8ac7`, fails: https://github.com/status-im/nim-beacon-chain/pull/1339

**Comment by tersec** [comment]
Maybe resolved well enough by https://github.com/status-im/nim-beacon-chain/pull/1336 -- if that proves not to be true, a similar revert commit PR can be recreated if desired.

**Pull request closed without merging**
