### PR TITLE
lightweight stack traces

### PR DESCRIPTION
**Pull request by stefantalpalaru**
plus some light test runner refactoring and some Makefile cosmetic changes

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
Some benchmark numbers seem to be in order. I've run this on a laptop with an i7-4810MQ CPU, limiting it to 2 cores using taskset.

I've started by disabling libbacktrace from the default Nim flags:

```diff
diff --git a/Makefile b/Makefile
index d5794f6..1eaf606 100644
--- a/Makefile
+++ b/Makefile
@@ -60,7 +60,7 @@ endif
 
 # "--import" can't be added to config.nims, for some reason
 # "--define:release" implies "--stacktrace:off" and it cannot be added to config.nims either
-NIM_PARAMS := $(NIM_PARAMS) -d:release --import:libbacktrace
+#NIM_PARAMS := $(NIM_PARAMS) -d:release --import:libbacktrace
 
 #- the Windows build fails on Azure Pipelines if we have Unicode symbols copy/pasted here,
 #  so we encode them in ASCII
diff --git a/beacon_chain.nimble b/beacon_chain.nimble
index 1596109..f794662 100644
--- a/beacon_chain.nimble
+++ b/beacon_chain.nimble
@@ -42,7 +42,8 @@ proc buildBinary(name: string, srcDir = "./", params = "", cmdParams = "", lang
   var extra_params = params
   for i in 2..<paramCount():
     extra_params &= " " & paramStr(i)
-  exec "nim " & lang & " --out:./build/" & name & " -r -d:release --import:libbacktrace " & extra_params & " " & srcDir & name & ".nim" & " " & cmdParams
+  # exec "nim " & lang & " --out:./build/" & name & " -r -d:release --import:libbacktrace " & extra_params & " " & srcDir & name & ".nim" & " " & cmdParams
+  exec "nim " & lang & " --out:./build/" & name & " -r " & extra_params & " " & srcDir & name & ".nim" & " " & cmdParams
 
 ### tasks
 task test, "Run all tests":
```

Nim's default stack tracing mechanism: `rm -rf nimcache; time { taskset -a -c 0,2 make NIMFLAGS="--parallelBuild:2 -d:debug" -j2; taskset -a -c 0,2 make NIMFLAGS="--parallelBuild:2 -d:debug" test; }` (`--opt:speed` is still active here):

```text
real	27m23.669s
user	36m21.043s
sys	1m27.370s
```

The libbacktrace-based alternative: `rm -rf nimcache; time { taskset -a -c 0,2 make NIMFLAGS="--parallelBuild:2 -d:release --import:libbacktrace" -j2; taskset -a -c 0,2 make NIMFLAGS="--parallelBuild:2 -d:release --import:libbacktrace" test; }`:

```text
real	12m4.404s
user	18m19.575s
sys	1m20.995s
```

Let's see how much of that difference is in the tool building phase.

`rm -rf nimcache; time { taskset -a -c 0,2 make NIMFLAGS="--parallelBuild:2 -d:debug" -j2; }`:

```text
real	5m11.226s
user	9m39.265s
sys	0m40.423s
```

`rm -rf nimcache; time { taskset -a -c 0,2 make NIMFLAGS="--parallelBuild:2 -d:release --import:libbacktrace" -j2; }`:

```text
real	3m52.893s
user	7m5.320s
sys	0m38.465s
```

There's still some compilation being done inside `make test`, but it's clear that most of the gains are at runtime.

**Comment by arnetheduck** [comment]
I don't think there's any disagreement of this being a good change - however, it's a matter of priorities - this is non-crucial compared to working out a good automated finalization test suite, as well as other going-to-production issues of testnets and test benches overall

**Comment by stefantalpalaru** [comment]
Fresh benchmarks, on the same machine as 7 months ago:

Nim's default stack traces | nim-libbacktrace | libbacktrace is...
---------------------------------|-----------------------|--------------------------
`rm -rf nimcache; time taskset -a -c 0,2 make USE_LIBBACKTRACE=0 NIMFLAGS="--parallelBuild:2" -j2` | `rm -rf nimcache; time taskset -a -c 0,2 make NIMFLAGS="--parallelBuild:2" -j2` |
real	16m46.896s | real	13m51.634s | 17.40% faster
`rm -rf nimcache; time taskset -a -c 0,2 make USE_LIBBACKTRACE=0 NIMFLAGS="--parallelBuild:2" test` | `rm -rf nimcache; time taskset -a -c 0,2 make NIMFLAGS="--parallelBuild:2" test` |
real	19m52.543s | real	16m44.065s | 15.80% faster

**And a benchmark I can't fit in a nice table:**

## Nim's default stack traces

```text
rm -rf nimcache; make USE_LIBBACKTRACE=0 ncli_db; ./build/ncli_db bench --db=build/data/shared_medalla_0/db --network=medalla --slots=1000

     Average,       StdDev,          Min,          Max,      Samples,         Test
Validation is turned off meaning that no BLS operations are performed
    3179.692,        0.000,     3179.692,     3179.692,            1, Initialize DB
       0.662,        0.484,        0.087,        6.438,          721, Load block from database
      15.770,        0.000,       15.770,       15.770,            1, Load state from database
      17.539,        7.380,        9.420,      178.914,          690, Apply block
     578.035,      134.675,       43.260,      896.559,           31, Apply epoch block
       0.000,        0.000,        0.000,        0.000,            0, Database block store
```

## nim-libbacktrace

```text
rm -rf nimcache; make ncli_db; ./build/ncli_db bench --db=build/data/shared_medalla_0/db --network=medalla --slots=1000

     Average,       StdDev,          Min,          Max,      Samples,         Test
Validation is turned off meaning that no BLS operations are performed
    2389.382,        0.000,     2389.382,     2389.382,            1, Initialize DB (24.85% faster)
       0.192,        0.180,        0.030,        2.792,          721, Load block from database (70.99% faster)
      11.377,        0.000,       11.377,       11.377,            1, Load state from database (27.85% faster)
      15.192,        6.525,        8.215,      160.456,          690, Apply block (13.38% faster)
     230.133,       40.053,       32.202,      279.084,           31, Apply epoch block (60.18% faster)
       0.000,        0.000,        0.000,        0.000,            0, Database block store
```

**Comment by arnetheduck** [comment]
can you rerun the benchmark with `-d:release --passc:-flto --passl:-flto`?

**Comment by stefantalpalaru** [comment]
## -d:release

Now, `-d:release` on its own disables Nim's default stack traces, so we actually need `-d:release --stacktrace:on --excessiveStackTrace:on --linetrace:on`.

default stack traces | default stack traces + `-d:release` & friends | `-d:release` is...
-------------------------|----------------------------------------------------------|-------------------
rm -rf nimcache; time taskset -a -c 0,2 make USE_LIBBACKTRACE=0 NIMFLAGS="--parallelBuild:2" -j2 | rm -rf nimcache; time taskset -a -c 0,2 make USE_LIBBACKTRACE=0 NIMFLAGS="--parallelBuild:2 -d:release --stacktrace:on --excessiveStackTrace:on --linetrace:on" -j2 |
real	16m46.896s | real	16m13.492s | 3.31% faster
rm -rf nimcache; time taskset -a -c 0,2 make USE_LIBBACKTRACE=0 NIMFLAGS="--parallelBuild:2" test | rm -rf nimcache; time taskset -a -c 0,2 make USE_LIBBACKTRACE=0 NIMFLAGS="--parallelBuild:2 -d:release --stacktrace:on --excessiveStackTrace:on --linetrace:on" test |
real	19m52.543s | real	19m47.251s | same

### default stack traces

```text
rm -rf nimcache; make USE_LIBBACKTRACE=0 ncli_db; ./build/ncli_db bench --db=build/data/shared_medalla_0/db --network=medalla --slots=1000

     Average,       StdDev,          Min,          Max,      Samples,         Test
Validation is turned off meaning that no BLS operations are performed
    3179.692,        0.000,     3179.692,     3179.692,            1, Initialize DB
       0.662,        0.484,        0.087,        6.438,          721, Load block from database
      15.770,        0.000,       15.770,       15.770,            1, Load state from database
      17.539,        7.380,        9.420,      178.914,          690, Apply block
     578.035,      134.675,       43.260,      896.559,           31, Apply epoch block
       0.000,        0.000,        0.000,        0.000,            0, Database block store
```

### default stack traces + `-d:release` & friends

```text
rm -rf nimcache; make USE_LIBBACKTRACE=0 NIMFLAGS="--parallelBuild:2 -d:release --stacktrace:on --excessiveStackTrace:on --linetrace:on" ncli_db; ./build/ncli_db bench --db=build/data/shared_medalla_0/db --network=medalla --slots=1000

     Average,       StdDev,          Min,          Max,      Samples,         Test
Validation is turned off meaning that no BLS operations are performed
    3174.192,        0.000,     3174.192,     3174.192,            1, Initialize DB
       0.645,        0.444,        0.078,        4.155,          721, Load block from database
      15.207,        0.000,       15.207,       15.207,            1, Load state from database
      17.378,        7.373,        9.170,      178.882,          690, Apply block
     578.500,      133.874,       43.242,      886.992,           31, Apply epoch block
       0.000,        0.000,        0.000,        0.000,            0, Database block store
```

## LTO

default stack traces + LTO | libbacktrace + LTO | libbacktrace is...
----------------------------------|-------------------------|----------------------
rm -rf nimcache; time taskset -a -c 0,2 make USE_LIBBACKTRACE=0 NIMFLAGS="--parallelBuild:2 --passC:-flto --passL:-flto" -j2 | rm -rf nimcache; time taskset -a -c 0,2 make NIMFLAGS="--parallelBuild:2 --passC:-flto --passL:-flto" -j2 |
real	12m55.851s | real	12m24.029s | 4.10% faster
rm -rf nimcache; time taskset -a -c 0,2 make USE_LIBBACKTRACE=0 NIMFLAGS="--parallelBuild:2 --passC:-flto --passL:-flto" test | rm -rf nimcache; time taskset -a -c 0,2 make NIMFLAGS="--parallelBuild:2 --passC:-flto --passL:-flto" test |
real	16m30.010s | real	14m44.121s | 10.69% faster

### default stack traces + LTO

```text
rm -rf nimcache; make USE_LIBBACKTRACE=0 NIMFLAGS="--passC:-flto --passL:-flto" ncli_db; ./build/ncli_db bench --db=build/data/shared_medalla_0/db --network=medalla --slots=1000

     Average,       StdDev,          Min,          Max,      Samples,         Test
Validation is turned off meaning that no BLS operations are performed
    3013.824,        0.000,     3013.824,     3013.824,            1, Initialize DB
       0.519,        0.346,        0.067,        3.016,          721, Load block from database
      15.750,        0.000,       15.750,       15.750,            1, Load state from database
      17.702,        7.390,        9.383,      178.326,          690, Apply block
     559.509,      136.950,       38.120,      897.047,           31, Apply epoch block
       0.000,        0.000,        0.000,        0.000,            0, Database block store
```

### libbacktrace + LTO

```text
rm -rf nimcache; make NIMFLAGS="--passC:-flto --passL:-flto" ncli_db; ./build/ncli_db bench --db=build/data/shared_medalla_0/db --network=medalla --slots=1000

     Average,       StdDev,          Min,          Max,      Samples,         Test
Validation is turned off meaning that no BLS operations are performed
    2366.455,        0.000,     2366.455,     2366.455,            1, Initialize DB (21.47% faster)
       0.199,        0.162,        0.032,        2.749,          721, Load block from database (61.65% faster)
      11.312,        0.000,       11.312,       11.312,            1, Load state from database (28.17% faster)
      15.073,        6.305,        8.353,      155.199,          690, Apply block (14.85% faster)
     159.286,       27.507,       24.845,      189.551,           31, Apply epoch block (71.53% faster)
       0.000,        0.000,        0.000,        0.000,            0, Database block store
```

## Conclusions

I'm not going to throw away that small 3.31% compilation time gain from `-d:release` & friends, which is probably due to not having to compile some stdlib code. PR incoming.

LTO works much better with libbacktrace for "apply epoch block". At the same time, while improving the performance of Nim's default stack traces, it can't compete with the improvements provided by libbacktrace.

**Pull request merged**
