### PR TITLE
Allow to specify rpcAddress and metricsAddress in SCRIPT_PARAMS.

### PR DESCRIPTION
**Pull request by cheatfate**
This PR will allow to use `rpc-address` and `metrics-address` options of `beacon_node` in `connect_to_testnet` script.
For example:

```make SCRIPT_PARAMS="--rpc-address:8.8.8.8 --metrics-address:8.8.8.8" altona```

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
Can we convince confutils to accept an arbitrary number of options it should not parse, so we can feed them to `beacon_node`?

If not the usual `--foo --bar altona -- --dont --parse --these`, then something like `--foo --bar --extraOpts="--dont --parse --these"`.

So we don't keep duplicating beacon_node options here.

**Comment by zah** [comment]
Yes, this use case popped up in testutils as well. I'll look into it, shouldn't be too hard to add a special type that collects arbitrary options.

**Comment by stefantalpalaru** [comment]
In the mean time, can we use the second format I proposed?

**Comment by zah** [comment]
Not yet, there is no special support for this as well.

**Comment by stefantalpalaru** [comment]
No special support needed. It's just a string option value.

**Comment by stefantalpalaru** [comment]
Implemented in: https://github.com/status-im/nim-beacon-chain/pull/1264

**Pull request merged**
