### PR TITLE
new build system and submodules

### PR DESCRIPTION
**Pull request by stefantalpalaru**

### CODE REVIEW

**Comment by zah** [comment]
Hmm, wouldn't it be better to add Nim and Nim-csources as submodules to `nimbus-build-system`. Just today I was considering adding `nvm` there as well after looking at the needed steps to integrate https://github.com/status-im/thundercloud

**Comment by stefantalpalaru** [comment]
You can argue that Nim, Nim-csources and nimble will be required by all projects using nimbus-build-system, but can we say the same about nvm?

**Comment by stefantalpalaru** [comment]
Another problem is path length. Say you need to use a Nim/Nimble binary directly. It would be "vendor/nimbus-build-system/vendor/Nim/bin/nim" instead of "vendor/Nim/bin/nim".

**Comment by stefantalpalaru** [comment]
I don't think the 32-bit Windows failure has anything to do with this PR. Ready for merging.

**Comment by zah** [comment]
> Another problem is path length. Say you need to use a Nim/Nimble binary directly. It would be "vendor/nimbus-build-system/vendor/Nim/bin/nim" instead of "vendor/Nim/bin/nim".

Considering that `nim` should be in your PATH, perhaps this is less of a problem. But you can probably skip the `vendor` dir in nimbus-build-system itself.

> You can argue that Nim, Nim-csources and nimble will be required by all projects using nimbus-build-system, but can we say the same about nvm?

I think we can think of 'numbus-build-system' as "common build-related tools". `nvm` is a certainly on the fence here, but you don't pay much for it if you don't use it.

**Comment by stefantalpalaru** [comment]
> Considering that nim should be in your PATH, perhaps this is less of a problem.

Yes, but "nimble" is now a function defined in "env.sh" that runs "nimble.sh", so if you want the actual Nimble binary, you need the full path.

**Comment by zah** [comment]
You can add another alias or an env var pointing to the real nimble perhaps.

**Comment by arnetheduck** [comment]
tested, wfm.

**Comment by tersec** [comment]
wfm

**Pull request merged**
