### PR TITLE
Bellatrix metadata for Mainnet

### PR DESCRIPTION
**Pull request by zah**

### CODE REVIEW

**Comment by etan-status** [comment]
`beacon_chain/spec/presets.nim` needs a bump as well.

**Comment by zah** [comment]
I would say it needs refactoring - using any constant from there which should have been read from the run-time config is a potential bug. But are you talking about files such as `bellatrix_preset.nim` or to the definition of the `RuntimeConfig` (e.g. missing fields, etc).

**Comment by zah** [comment]
Nevermind, found out what you meant!

**Comment by zah** [comment]
In `presets.nim`, there is a constant `defaultRuntimeConfig` which holds values that will be used as defaults in case the network specific run-time config doesn't override them. The specs currently don't specify what should be the treatment of configs with missing values, but the Gnosis network is known to use such configs with the expectation that "all other settings are the same as mainnet". This seems relatively reasonable for most settings, but it's a bit less clear about values such as `TERMINAL_TOTAL_DIFFICULTY` and `X_FORK_EPOCH`. A more appropriate conservative stance would be to assign these parameters to known safe values such as "far future epoch" until the network config hasn't specified them explicitly.

**Review by tersec — APPROVED** [review]

**Pull request merged**
