### PR TITLE
add option to disable discv5

### PR DESCRIPTION
**Pull request by arnetheduck**

### CODE REVIEW

**Comment by zah** [comment]
What we know about the testnet simulation right now is that it's dependent on the discovery seen tables (which control how much time the node would wait before trying to connect to one of the bootstrap nodes again after an initial failure). This tells us that we have a problem with the initial connections and we need retries. By disabling discovery, the whole retry mechanism is disabled and the needed links are never established.

**Comment by arnetheduck** [comment]
otoh the simulation runs under perfect conditions and should never ever disconnect - it's almost a better test if it doesn't reconnect

**Comment by zah** [comment]
My message meant to explain why you see the finalization test failing right now. It's not a matter of back luck, but a consequence of an underlying problem.

**Comment by kdeme** [comment]
> otoh the simulation runs under perfect conditions and should never ever disconnect - it's almost a better test if it doesn't reconnect

It is not about disconnecting. It is about an initial failure to connect, even though libp2p should be "ready". I think even with  disabling discovery, you can still see this failure. 

https://github.com/status-im/nim-beacon-chain/pull/1494 is probably the better solution in the way things are currently set up with discovery. 

Nevertheless, @zah has a point that it would be good to know why there is that initial failure.

**Pull request merged**
