### PR TITLE
[WIP, don't merge] Add compile-time `fake_bls` flag to accept invalid signatures as valid.

### PR DESCRIPTION
**Pull request by gnattishness**
This is a proposal for a compile-time flag to expose a consistent bls interface, but accept invalid signatures as valid.

It's currently pretty messy but wanted to get some feedback and discussion before refining further.

An alternative approach to the `skipBLSValidation` runtime flag discussed in #407.

Compile with `-d:fake_bls` to enable.

### Why?

Useful for tests e.g. fuzzing where performance is important and disabling bls verification allows more code coverage. For differential fuzzing (e.g. [`beacon-fuzz`](https://github.com/sigp/beacon-fuzz)) each client must implement consistent functionality. Other implementations currently have the ability to `verify_state_root` with bls disabled (not currently possible in Nimbus: #407)

### Why compile-time?

Improved performance, and can be adjusted with a single flag rather than passing a `flags` variable around everywhere.

### Other details

- Passes all tests when not enabled.
- Currently passes all tests (e.g. `NIMFLAGS="-d:fake_bls" make test`) when enabled, except for ones that expect an invalid signature to be rejected.

### CODE REVIEW

**Comment by gnattishness** [comment]
I'd initially tried having the fake and real implementations in separate files, with `crypto.nim` containing the common functions and `include`ing them, but `{.experimental: "codeReordering".}` does not appear to execute after the `include`.

Using import could be neater, but would need something like `crypto.nim` importing `bls.nim` or `fake_bls.nim`, both importing a `common_bls.nim`. I'm not too happy about the levels of indirection this creates and might still have cyclic import issues.

**Comment by arnetheduck** [comment]
FYI, constant flags can generally be propagated down to where they used meaning there will be no performance difference with the right compiler options (LTO mainly, which we currently don't enable yet). We also tend to avoid compile-time `when` jungles because they're hard to test and keep up to date - I'd prefer seeing the flags reused for this.

**Comment by gnattishness** [comment]
> I'd prefer seeing the flags reused for this
Appreciate the feedback, I'm happy to rework in that case. I'll get back to you

**Comment by zah** [comment]
Considering how "fake" the fake BLS is, I would personally vote for the compile-time option. 

Inter-procedural constant propagation is possible only if the code gets inlined and here this must apply to the complex multi-line state transition functions that are unlikely to be completely inlined in the fuzzer.

**Comment by gnattishness** [comment]
Closing in favor of #735

**Pull request closed without merging**
