### PR TITLE
bump vendor/nimbus-build-system

### PR DESCRIPTION
**Pull request by stefantalpalaru**
The relevant change is that we now limit the number of Nim compiler binaries we accumulate in "vendor/nimbus-build-system/vendor/Nim/bin/".

### CODE REVIEW

**Review by arnetheduck — APPROVED** [review]

**Comment by etan-status** [comment]
Seeing some spurious `ls: vendor/nimbus-build-system/vendor/Nim/bin/nim_commit_*: No such file or directory`
Could this need a `nullglob`?

https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnimbus-eth2%2Fmultibranch/detail/bump-nbs/1/pipeline/91/

**Comment by etan-status** [comment]
Seeing some spurious `ls: vendor/nimbus-build-system/vendor/Nim/bin/nim_commit_*: No such file or directory`
Could this need a `nullglob`?

https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnimbus-eth2%2Fmultibranch/detail/bump-nbs/1/pipeline/91/

**Comment by stefantalpalaru** [comment]
`2>/dev/null` will do the trick.

**Comment by stefantalpalaru** [comment]
Fixed.

**Review by etan-status — APPROVED** [review]

**Pull request merged**
