### PR TITLE
some whole-file copies from altair branch

### PR DESCRIPTION
**Pull request by tersec**
- 6 whole files (with empty lines at the end removed, where they'd been added)
- nimbus_beacon_node minimally adjusted in one line to fix a `ConnectionState`/`GossipState` enum identifier ambiguity
- doesn't overlap with https://github.com/status-im/nimbus-eth2/pull/2727

### CODE REVIEW

**Comment by arnetheduck** [comment]
for the sync committtes etc, I think it's a good opportunity to slow down a little with the merges and make sure we have test coverage - ie how's it looking on that front?

the other code we've merged have been mainly refactorings and preparations, this however is new functionality that needs coverage

**Comment by tersec** [comment]
Not sure, @zah has been working on sync committees, so I haven't followed it in as much detail as some of the rest.

**Comment by arnetheduck** [comment]
presumably, sync committe stuff is part of the upstream test suite though?

**Comment by tersec** [comment]
Sure, but state transition aspects, not the `spec/signatures.nim` parts. I'm not sure `spec/signatures.nim` has tests in general, to be fair.

**Comment by tersec** [comment]
https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/mainnet/altair/operations/sync_aggregate/pyspec_tests

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/2728/commits/0d95a4a9bcc228b67a9b3e456e5dd7cefd8c9c09 preserves the refactoring aspect.

**Review by arnetheduck — APPROVED** [review]

**Pull request merged**
