### PR TITLE
Command-line and data storage handling for testnets

### PR DESCRIPTION
**Pull request by zah**

### CODE REVIEW

**Comment by cheatfate** [comment]
Looks like here hidden one more dependency `curl`.

**Comment by zah** [comment]
@cheatfate, this is a temporary thing. Will be replaced by a proper HTTP client in the future. I considered implementing a client in `httputils`, but postponed it for now.

**Comment by zah** [comment]
Merging now, because otherwise the build may be broken for you with the latest `confutils` revision.

**Comment by arnetheduck** [comment]
longer term, I don't think we should have any kind of http downloading in there - we should be connecting to the network and syncing everything from there. ie provide a single merkle root and boot node, and from there, it should download everything necessary, including state etc, no http involved.

**Pull request merged**
