### PR TITLE
ci: use clang 18 from Homebrew on aarch64

### PR DESCRIPTION
**Pull request by jakubgs**
Not sure if `LDFLAGS` and `CPPFLAGS` are absolutely necessary but Brew docs recommend it.

Depends on:
- [`infra-ci#67fafcb5`](https://github.com/status-im/infra-ci/commit/67fafcb5) - ci-slave-macos: install llvm 17 for newer clang
- https://github.com/status-im/status-jenkins-lib/pull/90

### CODE REVIEW

**Comment by jakubgs** [comment]
Doesn't seem to like `llvm@17`:
```
Building: build/test_libnimbus_lc
beacon_chain/libnimbus_lc/test_libnimbus_lc.c:54:5: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
   54 |     buffer[size] = '\0';
      |     ^~~~~~
beacon_chain/libnimbus_lc/test_libnimbus_lc.c:96:24: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
   96 |         printf("%02x", bytes_[i]);
      |                        ^~~~~~
beacon_chain/libnimbus_lc/test_libnimbus_lc.c:105:24: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
  105 |         printf("%02x", bytes_[i]);
      |                        ^~~~~~
beacon_chain/libnimbus_lc/test_libnimbus_lc.c:119:17: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
  119 |             if (value.bytes[i]) {
      |                 ^~~~~~~~~~~
beacon_chain/libnimbus_lc/test_libnimbus_lc.c:130:70: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
  130 |             uint16_t temp = (uint16_t) ((uint16_t) remainder << 8) | value.bytes[i];
      |                                                                      ^~~~~~~~~~~
beacon_chain/libnimbus_lc/test_libnimbus_lc.c:131:13: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
  131 |             value.bytes[i] = (uint8_t) (temp / 10);
      |             ^~~~~~~~~~~
beacon_chain/libnimbus_lc/test_libnimbus_lc.c:134:9: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
  134 |         weiString[o++] = '0' + (char) remainder;
      |         ^~~~~~~~~
beacon_chain/libnimbus_lc/test_libnimbus_lc.c:137:9: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
  137 |         weiString[o++] = '0';
      |         ^~~~~~~~~
beacon_chain/libnimbus_lc/test_libnimbus_lc.c:144:26: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
  144 |             printf("%c", weiString[--o]);
      |                          ^~~~~~~~~
beacon_chain/libnimbus_lc/test_libnimbus_lc.c:148:21: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
  148 |     while (z < o && weiString[z] == '0') {
      |                     ^~~~~~~~~
beacon_chain/libnimbus_lc/test_libnimbus_lc.c:154:26: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
  154 |             printf("%c", weiString[--o]);
      |                          ^~~~~~~~~
11 errors generated.
```

**Comment by tersec** [comment]
Well, `-Wno-unsafe-buffer-usage` would solve this.

https://stackoverflow.com/questions/77017567/how-to-fix-code-to-avoid-warning-wunsafe-buffer-usage

https://www.devgem.io/posts/how-to-address-the-wunsafe-buffer-usage-warning-in-clang

It seems like it's a rather zealous warning, overzealous maybe even. The `-Werror` is from `nimbus-eth2`'s own `Makefile`.

But short term, probably disable that warning, which comes from `-Weverything`, and get this PR mergeable.

**Comment by etan-status** [comment]
May also need `-Wno-unknown-warning-option` so that the older clang which doesn't know yet about this new warning won't bail.

**Comment by jakubgs** [comment]
Okay, now only `x86_64` has some bizarre issue:
```
/var/folders/ks/5chrbv156ybfyr8g02znf0lr0006vn/T/assembly-e81b13.s:1472:1: error: invalid CFI advance_loc expression
.cfi_adjust_cfa_offset 8
^
/var/folders/ks/5chrbv156ybfyr8g02znf0lr0006vn/T/assembly-e81b13.s:6555:1: error: invalid CFI advance_loc expression
.cfi_adjust_cfa_offset 8
^
/var/folders/ks/5chrbv156ybfyr8g02znf0lr0006vn/T/assembly-e81b13.s:6673:1: error: invalid CFI advance_loc expression
.cfi_adjust_cfa_offset 8
...
```
I'll try to see if it's consistent across different hosts.

**Comment by jakubgs** [comment]
It appears this issue is not specific to `maci7-02`, and it fails the same way on `maci7-01`:
```
07:43:46  Building: build/ncli_db
07:43:49  /var/folders/kb/g1563gf912j8s81z0klrpxrr0006vn/T/assembly-f4eb15.s:1472:1: error: invalid CFI advance_loc expression
07:43:49  .cfi_adjust_cfa_offset 8
07:43:49  ^
07:43:49  /var/folders/kb/g1563gf912j8s81z0klrpxrr0006vn/T/assembly-f4eb15.s:6555:1: error: invalid CFI advance_loc expression
07:43:49  .cfi_adjust_cfa_offset 8
07:43:49  ^
```
https://ci.status.im/job/nimbus-eth2/job/platforms/job/macos/job/x86_64/job/PR-6153/10/console

**Comment by tersec** [comment]
- https://github.com/supranational/blst/issues/209
maybe

**Comment by tersec** [comment]
Also https://reviews.llvm.org/D153167 is the clang/LLVM change triggering this. WINE was hit too: https://bugs.winehq.org/show_bug.cgi?id=55863

**Comment by tersec** [comment]
The underlying issue doesn't seem to show up on anything but macOS aarch64, so one option might be to only use Homebrew clang 17 on that aarch64, not x86, macOS.

**Comment by jakubgs** [comment]
Of course, just my luck to get edge cases like this.

I wonder if it's all versions of LLVM 17 or if there's some specific minor release that isn't affected. If so we could try to target a specific one, we could do that with Nix instead of Brew, which would also be more effectively pinned.

**Comment by tersec** [comment]
> Of course, just my luck to get edge cases like this.
> 
> I wonder if it's all versions of LLVM 17 or if there's some specific minor release that isn't affected. If so we could try to target a specific one, we could do that with Nix instead of Brew, which would also be more effectively pinned.

https://github.com/llvm/llvm-project/commit/0b0672773e8b2ed01ad3fce103f4d84becfdd1ed which is the first commit here shows up in https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.0-rc1 so probably it affects every version of LLVM 17.

**Comment by jakubgs** [comment]
>one option might be to only use Homebrew clang 17 on that aarch64, not x86, macOS.

I'm cringing just thinking about it. What about going further to 18?

**Comment by tersec** [comment]
> > one option might be to only use Homebrew clang 17 on that aarch64, not x86, macOS.
> 
> I'm cringing just thinking about it. What about going further to 18?

Sure, why not

**Comment by jakubgs** [comment]
It appears LLVM 18 is not yet available in Homebrew:

* https://github.com/Homebrew/homebrew-core/pull/165206

**Comment by tersec** [comment]
I suspect clang 18 doesn't/won't compile BLST on macOS x86 for the same reason clang 17 doesn't. It doesn't seem like this is a clang 17 bug, but a new constraint they're checking for that target platform. There's still no externally visible evidence BLST is responding to/caring about this particular breakage, on their end, but a likely eventual resolution might be that BLST fixes this, `nimbus-eth2` updates to that BLST release, and then clang 17 works for `nimbus-eth2`.

**Comment by jakubgs** [comment]
You're right, it still fails even with LLVM 18 on `x86_64`:
```

[2024-04-23T08:47:20.443Z] Building: build/ncli_db
[2024-04-23T08:47:26.785Z] /var/folders/ks/5chrbv156ybfyr8g02znf0lr0006vn/T/assembly-5eeab4.s:1472:1: error: invalid CFI advance_loc expression
[2024-04-23T08:47:26.785Z] .cfi_adjust_cfa_offset 8
[2024-04-23T08:47:26.785Z] ^
[2024-04-23T08:47:26.785Z] /var/folders/ks/5chrbv156ybfyr8g02znf0lr0006vn/T/assembly-5eeab4.s:6555:1: error: invalid CFI advance_loc expression
[2024-04-23T08:47:26.785Z] .cfi_adjust_cfa_offset 8
[2024-04-23T08:47:26.785Z] ^
```
https://ci.status.im/job/nimbus-eth2/job/platforms/job/macos/job/x86_64/job/main/job/PR-6153/11/console

**Review by tersec — APPROVED** [review]

**Pull request merged**
