### PR TITLE
prune `validatorIndexFromPubKey` table

### PR DESCRIPTION
**Pull request by arnetheduck**

### CODE REVIEW

**Comment by cheatfate** [comment]
I had no idea that we have such table, do we have an interface to query this table?

Such table will be used in REST/RPC, because there validator identifiers passed in requests could be either `index` or `pubkey`. When it `index` we are efficient, but as soon as it `pubkey`, we iterating over the whole list of validators and perform pubkey comparison for every validator (and this is very inefficient).

Our current approach (ineffective):
https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/rpc/beacon_api.nim#L267-L278
https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/rpc/beacon_rest_api.nim#L240-L268

**Comment by tersec** [comment]
Why should such a table be in sqlite database? To the extent it's necessary to be able to efficiently look up validator index from pubkey, adding a persistent schema dependency which has to be managed, migrated, and otherwise creates unnecessary compatibility and disk I/O failure modes seems not worth the memory. Better to have it constructed in memory once and maintained incrementally without outliving any given Nimbus node instance.

**Comment by cheatfate** [comment]
I'm fine with any type of interface "in-memory" or "in-database", because its much more efficient than we have right now. Also i think its much better to use some kind of tree structure, but of course we can start with `Table`. I'm just not sure how long it takes to build such structure.

**Comment by tersec** [comment]
Yes, eventually some kind of tree structure, or something else more sophisticated than just a list or table or array, may become necessary, as the number of validators grows, while the number of active validators eventually plateaus. That's a low priority, I'd say, even throughout the next several months or year, though.

**Comment by arnetheduck** [comment]
> I'm just not sure how long it takes to build such structure.

the linear scan over the validator set is actually "quite" fast - it didn't make sens to build a Table for example, for this purpose, in the spec - ie in the spec, we do this pubkey scan when processing deposits and it barely registers in performance traces, compared to doing the signature check. I'd generally say that unless we confirm it as a specific performance problem through measurements, we can continue doing linear scans for the REST api for now at least. 

That said, there's a few ways this _could_ be done, that make sense: the pubkey of each validator is copied into several places like caches etc - consolidating all these places would give room for an additional index, but above all, it would consolidate the logic for keeping the cache up to date.

**Pull request merged**
