### PR TITLE
[Fuzzing] Rebase libnfuzz to devel

### PR DESCRIPTION
**Pull request by gnattishness**
Add to devel.
NOTE: the following isn't 0.10.0 compatible yet, but doesn't affect `make test`

### CODE REVIEW

**Comment by gnattishness** [comment]
Applies #701 to devel.

**Comment by tersec** [comment]
Says applies to `devel`, but:
```
gnattishness wants to merge 1 commit into status-im:master from gnattishness:libnfuzz_rebase_to_devel
```
?

**Comment by zah** [comment]
Merged manually in https://github.com/status-im/nim-beacon-chain/commit/4f6f2f28f3d45a255e23b5bab8b0823d6a9a5058

**Comment by gnattishness** [comment]
Ah sorry about that! Thanks!

**Pull request closed without merging**
