### PR TITLE
drop rlpx support

### PR DESCRIPTION
**Pull request by arnetheduck**
* unmaintained dead code
* remove surface area of potential issues (imports, security issues, compiler bugs etc)

### CODE REVIEW

**Comment by zah** [comment]
This feels premature. Since the daemon doesn't offer any good ways to instrument the networking code, the native back-ends are valuable tools for debugging networking issues. We do have the native libp2p implementation nowadays, but I'd like to see it more actively used by everyone before we pull the plug on RLPx. As the code stands now, there is little benefit in removing a bunch of when statements (this PR changes nothing when `network_type` is not set to `rlpx`).

**Comment by zah** [comment]
> unmaintained dead code

In the past, when I needed rlpx, it took me less than 30 minutes to get it working. This wouldn't be the case after we merge this.

> remove surface area of potential issues (imports, security issues, compiler bugs etc)

The unused branches of when statements get very little processing in the compiler. I would estimate the risk to be extremely low.

**Comment by arnetheduck** [comment]
for nbc, it's time to focus on the product we'll actually audit and ship - rlpx is not part of it - we don't have time to maintain both as it stands so something needs to be cut - this code hasn't compiled for months, as such it is clearly not being used the way you're describing - it's still here in git should it ever be needed, but it would be better if whatever issues were solved in native libp2p instead of spending more time here.

**Comment by arnetheduck** [comment]
> The unused branches

and imports, and the weird gossipsub etc - also, in developing the api:s and features in the libp2p code, rlpx should not be a constraint or consideration - it's easier to refactor and fix other code if this code is not here

**Comment by zah** [comment]
I'm sure we can spend our time in more productive ways than arguing about this. For me, the cost of this code is nearly zero and the benefit of removing it now is nearly zero, but if you insist on doing this, I can live with it.

**Pull request merged**
