### PR TITLE
REST API test framework and tests.

### PR DESCRIPTION
**Pull request by cheatfate**

### CODE REVIEW

**Comment by mratsim** [comment]
What generates the json for testing?

**Comment by cheatfate** [comment]
@mratsim human person, in this particular case it was me :)

**Comment by arnetheduck** [comment]
I imagine this needs rebasing given the rest fixes?

**Comment by stefantalpalaru** [comment]
There's a weird failure mode: 10-12 minutes after generating a fresh testnet, these 3 test cases will fail: 247, 256 and 268.

After that interval, all tests pass consistently.

**Comment by stefantalpalaru** [comment]
Replicating the failure locally:

`rm -rf build/resttest_sim; ./tests/simulation/restapi.sh`

**Pull request merged**
