### PR TITLE
bump `nimbus-build-system` to `6cdd14282b7c813c2ae4b9a9d749c3ff5ce1b54a `

### PR DESCRIPTION
**Pull request by etan-status**
- Add GitHub Action CI
- Bump Nim to version 1.6.16
- switch to Nim `v1.6.16`

### CODE REVIEW

**Comment by etan-status** [comment]
note that this is a different Nim commit than the official `upstream` 1.6.16 tag, but the remaining changes seem to only affect their CI. not sure @jangko if that is intended.

**Comment by jangko** [comment]
Probably accidentally because iirc at that time upstream already two commits ahead and I forget to rewind.

**Comment by arnetheduck** [comment]
+1 for official tag default preference

**Comment by etan-status** [comment]
- https://github.com/status-im/nimbus-build-system/pull/70

**Pull request merged**
