### PR TITLE
Libp2p first failing commit (finalization triage)

### PR DESCRIPTION
**Pull request by sinkingsugar**

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
> add a sleep before starting next test node

You're thinking that the bootstrap node might be busy at start and it won't be listening to sockets when the other nodes start connecting?

BTW, how does that 30s connection timeout works? Is it just for a single connection, without retries in that interval?

**Comment by sinkingsugar** [comment]
> > add a sleep before starting next test node
> 
> You're thinking that the bootstrap node might be busy at start and it won't be listening to sockets when the other nodes start connecting?
Yeah I assume so

> BTW, how does that 30s connection timeout works? Is it just for a single connection, without retries in that interval?
I think @dryajov might be better at answering this, not sure on our timeout situation ( but I think it's unrelated here)

Also btw discovery will put any dial in a 10 mins backoff timer.. so if fails, that's triggered.. I tried reducing that timer and did not help.

**Comment by dryajov** [comment]
> > BTW, how does that 30s connection timeout works? Is it just for a single connection, without retries in that interval?

> I think @dryajov might be better at answering this, not sure on our timeout situation ( but I think it's unrelated here)

We don't really have any 30 seconds timeouts in libp2p, the timeout is in nbc https://github.com/status-im/nim-beacon-chain/blob/master/beacon_chain/eth2_network.nim#L1136-L1143

**Comment by arnetheduck** [comment]
this branch doesn't update libp2p though..?

**Comment by sinkingsugar** [comment]
> this branch doesn't update libp2p though..?

update for? there was no issue to fix libp2p side.

**Comment by tersec** [comment]
Is this PR/branch still useful?

**Comment by dryajov** [comment]
not really, I don't believe we need it anymore

**Pull request closed without merging**
