### PR TITLE
implement EIP-7514 for Deneb: Add Max Epoch Churn Limit

### PR DESCRIPTION
**Pull request by etan-status**
Cap activations per epoch according to EIP-7514:

- https://eips.ethereum.org/EIPS/eip-7514
- https://github.com/ethereum/consensus-specs/pull/3499

### CODE REVIEW

**Comment by etan-status** [comment]
needs 1.4.0-beta.2 tests but there are other changes needed to pass them, so hold back still

**Comment by etan-status** [comment]
- https://github.com/status-im/nimbus-eth2/pull/5444

**Comment by etan-status** [comment]
- https://github.com/status-im/nimbus-eth2/pull/5441

**Comment by etan-status** [comment]
- https://github.com/status-im/nimbus-eth2/pull/5445

**Review by tersec — APPROVED** [review]

**Pull request merged**
