### PR TITLE
Consensus object pools [reorg 4/5]

### PR DESCRIPTION
**Pull request by mratsim**
This consolidate block_pools, attestation_pool and exit_pool in the same consensus_object_pool folder.

Assumption for this folder:
- gossip validation has been done.

### CODE REVIEW

**Comment by arnetheduck** [comment]
how about removing `_pools`? I find it pretty confusing - could also call the thing `chain` which means there's various forms of chain data in it

**Comment by mratsim** [comment]
> how about removing `_pools`? I find it pretty confusing - could also call the thing `chain` which means there's various forms of chain data in it

`consensus_objects` alone seem like a `datatypes` repo.

`chain` is only true for blocks, the other objects (attestations, attester slashings, proposer slashings, voluntary exits) are free floating until they are integrated in a block. And even then, for blocks the chain is a DAG until finalization ;).

Also we will likely have other free floating objects in there in the future like cross-shard receipts or data availability proofs.

**Comment by arnetheduck** [comment]
well, pools is off for `chain_dag` for the same reason - ie by that time it's no longer a pool - the pools as mostly things needed for block and aggregate production, so yeah, `chain` might not be the best name either, as they contain pre-chain data.. @tersec maybe has some good ideas?

**Comment by tersec** [comment]
They're all used to construct beacon blocks for proposal. This is more specific than "consensus", broadly, and is more abstract than the mechanical aspects of whether they're "pools".

`block_proposal_objects` or `block_construction_objects`?

**Comment by mratsim** [comment]
The attestation pool is also used for aggregate so it's not just block proposal. And I expect the exit pool would be used for a slashing service.

I expect we will have more pools in phase 1 (cross-shard receipts, data availability proofs or fraud proofs at least)

For now I'll merge as is

**Pull request merged**
