### PR TITLE
Revert "Switch back to nim-websock"

### PR DESCRIPTION
**Pull request by tersec**
Reverts status-im/nimbus-eth2#3665

### CODE REVIEW

**Comment by arnetheduck** [comment]
what are the chances of making this a command-line parameter instead? cc @Menduist

**Comment by tersec** [comment]
> what are the chances of making this a command-line parameter instead? cc @Menduist

It can be a command-line parameter once it's out of the critical path and not preventing the Ropsten fleet from working.

**Comment by zah** [comment]
A run-time option would be difficult, but we can enable websock on some of our fleet nodes. We are already supporting custom compilation flags there.

**Comment by zah** [comment]
Compile-time setup for the fleet has been proposed here: https://github.com/status-im/infra-nimbus/pull/113
It requires https://github.com/status-im/nimbus-eth2/pull/3820 to be merged first.

**Pull request merged**
