### PR TITLE
Ctrl+C now stops the BN when waiting for genesis

### PR DESCRIPTION
**Pull request by onqtam**
This is the output which you would get if you Ctrl+C-ed while waiting for genesis:
```
INF 2020-09-28 11:09:16.773+03:00 Shutting down after having received SIGINT topics="beacnde" tid=4759 file=beacon_node.nim:1203

Traceback (most recent call last, using override)
/home/onqtam/nbc2/beacon_chain/mainchain_monitor.nim(545) main
/home/onqtam/nbc2/beacon_chain/mainchain_monitor.nim(538) NimMain
/home/onqtam/nbc2/beacon_chain/beacon_node.nim(1214) main
/home/onqtam/nbc2/vendor/nim-chronos/chronos/asyncloop.nim(945) waitFor
/home/onqtam/nbc2/vendor/nim-chronos/chronos/asyncloop.nim(276) poll
/home/onqtam/nbc2/vendor/nim-chronos/chronos/asyncmacro2.nim(66) checkForGenesisLoop_continue
/home/onqtam/nbc2/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(407) reportUnhandledError
/home/onqtam/nbc2/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(358) reportUnhandledErrorAux
Error: unhandled exception: Async procedure (&checkForGenesisLoop) yielded `nil`, are you await'ing a `nil` Future? [AssertionError]
make: *** [Makefile:313: spadina] Error 1
```
It's not perfect but at least the process terminates.

### CODE REVIEW

**Comment by arnetheduck** [comment]
eh, come on, we can do better than this?

**Comment by onqtam** [comment]
Ok, now it works properly - it doesn't just crash.

**Comment by sachayves** [comment]
can we merge to master?

**Comment by stefantalpalaru** [comment]
> can we merge to master?

Sure, by merging it into "devel" and then merging "devel" into "master".

**Comment by sachayves** [comment]
great. holding off announcing the Spadina page until we've done so

**Pull request merged**
