### PR TITLE
Libp2p connection limits

### PR DESCRIPTION
**Pull request by dryajov**
trying with the version of libp2p that's already in `unstable`.

### CODE REVIEW

**Comment by sinkingsugar** [comment]
@tersec @dryajov 
Gossipsub changes passed with auto bump and most of all they are irrelevant with scores disabled.
The peer thing is a fix from 50 to 160.
We can revert as much as we want but this failure is likely a bug that somehow was merged cos CI was green.
So rationalizing and checking logs:
```
{"lvl":"DBG","ts":"2021-01-26 14:03:03.477+00:00","msg":"Connection to remote peer failed","topics":"networking","tid":581242,"file":"eth2_network.nim:854","msg":"Too many connections","peer":"16U*GgFUTd","index":2}
```
This is a bug regardless I think, the testnet has only 4 peers.

**Comment by tersec** [comment]
2021-01-26-195738_867x572

**Comment by dryajov** [comment]
This branch also fails without this changes, so it seems like both are unrelated and the issue is somewhere else. BTW, the significant change in libp2p that this relies on, which is connection limits, also passed finalization and has been merged since last week.

**Comment by tersec** [comment]
It's also interesting that https://github.com/status-im/nimbus-eth2/pull/2263 seems to work fine.

**Comment by dryajov** [comment]
> It's also interesting that #2263 seems to work fine.

Yes, which includes the connection limits changes. To clarify, as it stands currently, libp2p has an arbitrary limit of 50 connections, which is much less that the one being passed here, which is 160. This means that both the #2263 and the previous libp2p bump, both passed finalization with the lower limit on connections.

**Comment by arnetheduck** [comment]
maxConnections is one limit for both directions whereas the default setup in libp2p is separate limits for each direction

**Comment by dryajov** [comment]
> maxConnections is one limit for both directions whereas the default setup in libp2p is separate limits for each direction

Not really, the default is `maxConnections` and `maxIn` and `maxOut` are separated, so the limit is set globally to 50 right now.

**Comment by dryajov** [comment]
I see lots of:

```
{"lvl":"WRN","ts":"2021-01-26 21:50:00.010+00:00","msg":"Caught an unexpected error","topics":"vc","tid":3231420,"file":"nimbus_validator_client.nim:249","err":"(111) Connection refused","slot":100}
{"lvl":"INF","ts":"2021-01-26 21:50:00.010+00:00","msg":"Slot end","topics":"vc","tid":3231420,"file":"nimbus_validator_client.nim:254","slot":100,"nextSlot":101,"portBN":7100}
{"lvl":"INF","ts":"2021-01-26 21:50:12.010+00:00","msg":"Slot start","topics":"vc","tid":3231420,"file":"nimbus_validator_client.nim:116","lastSlot":100,"scheduledSlot":101,"beaconTime":"20 minutes 12 seconds","portBN":7100}
{"lvl":"INF","ts":"2021-01-26 21:50:16.004+00:00","msg":"Slot end","topics":"vc","tid":3231420,"file":"nimbus_validator_client.nim:254","slot":101,"nextSlot":102,"portBN":7100}
{"lvl":"INF","ts":"2021-01-26 21:50:24.008+00:00","msg":"Slot start","topics":"vc","tid":3231420,"file":"nimbus_validator_client.nim:116","lastSlot":101,"scheduledSlot":102,"beaconTime":"20 minutes 24 seconds","portBN":7100}
{"lvl":"WRN","ts":"2021-01-26 21:50:28.004+00:00","msg":"Caught an unexpected error","topics":"vc","tid":3231420,"file":"nimbus_validator_client.nim:249","err":"(111) Connection refused","slot":102}
{"lvl":"INF","ts":"2021-01-26 21:50:28.004+00:00","msg":"Slot end","topics":"vc","tid":3231420,"file":"nimbus_validator_client.nim:254","slot":102,"nextSlot":103,"portBN":7100}
{"lvl":"INF","ts":"2021-01-26 21:50:36.009+00:00","msg":"Slot start","topics":"vc","tid":3231420,"file":"nimbus_validator_client.nim:116","lastSlot":102,"scheduledSlot":103,"beaconTime":"20 minutes 36 seconds","portBN":7100}
{"lvl":"WRN","ts":"2021-01-26 21:50:40.001+00:00","msg":"Caught an unexpected error","topics":"vc","tid":3231420,"file":"nimbus_validator_client.nim:249","err":"(111) Connection refused","slot":103}
```

Seems like the validator client is having issues connecting to the beacon node? What is it using, HTTP?

**Comment by sinkingsugar** [comment]
So it indeed was the script limit! Glad we found the cause!

**Pull request merged**
