### PR TITLE
Bump modules to deal with the Nim 1.2 upgrade

### PR DESCRIPTION
**Pull request by zah**
Work in progress. Many modules don't compile yet.

### CODE REVIEW

**Comment by arnetheduck** [comment]
this is wip/don't merge though until 1.2 is released?

**Comment by zah** [comment]
Yes

**Comment by tersec** [comment]
To what extent do the bumped modules also work with Nim 1.0.6?

**Comment by zah** [comment]
I've tried to make sure that everything with merged commits to `master` also works in 1.0.6. Some submodules require changes specific to Nim 1.2 and I've created branches named nim-1.2 in all such submodules.

**Comment by jangko** [comment]
this is the error message from CI

```text
[Suite] Official - Sanity - Slots  [Preset: minimal]
D:\a\1\s\vendor\nimbus-build-system\vendor\Nim\lib\system\fatal.nim(49) sysFatal

    Unhandled exception: D:\a\1\s\tests\helpers\debug_state.nim(51, 13) `stateRef.slot == postRef.slot` 
Diff: stateRef.slot = 226486149642715137
and   postRef.slot = 16
 [AssertionError]
```

and this is what I get locally:

```text
[Suite] Official - Sanity - Slots  [Preset: minimal]
F:\projects\status-beacon-chain\vendor\nimbus-build-system\vendor\Nim\lib\system\fatal.nim(49) sysFatal

    Unhandled exception: F:\projects\status-beacon-chain\tests\helpers\debug_state.nim(51, 13) `stateRef.slot == postRef.slot`
Diff: stateRef.slot = 465826127085043713
and   postRef.slot = 16
 [AssertionError]
```

similar error but the `stateRef.slot` value is different. is this something expected? I'm a bit confused.

same thing happened to [Preset: mainnet]

```text
# CI value:
Diff: stateRef.slot = 302484994650013697
and   postRef.slot = 64

# local value
Diff: stateRef.slot = 9397289341572612097
and   postRef.slot = 64
```

**Comment by stefantalpalaru** [comment]
Heap corruption on 32-bit?

64-bit Linux also shows different slot values (added debug prints locally):

```text
[amd] 38 Mon Apr 06 20:37:47 |/mnt/sda3/storage/CODE/status/nim-beacon-chain-clean|
stefan$ ./env.sh nim c -r --verbosity:0 --hints:off tests/official/test_fixture_sanity_slots.nim

[Suite] Official - Sanity - Slots  [Preset: minimal]
stateRef.slot = 4
postRef.slot = 12
[OK] Slots - over_epoch_boundary
stateRef.slot = 0
postRef.slot = 2
[OK] Slots - slots_2
stateRef.slot = 0
postRef.slot = 1
[OK] Slots - slots_1
stateRef.slot = 0
postRef.slot = 16
[OK] Slots - double_empty_epoch
stateRef.slot = 0
postRef.slot = 8
[OK] Slots - empty_epoch
```

**Comment by stefantalpalaru** [comment]
It's not Windows specific. 64-bit Linux host targetting 32-bit:

```text
[amd] 38 Mon Apr 06 20:51:46 |/mnt/sda3/storage/CODE/status/nim-beacon-chain-clean|
stefan$ ./env.sh nim c -r -d:disableLibbacktrace --cpu:i386 --passC:"-m32" --passL:-m32 --listCmd --verbosity:0 --hints:off tests/official/test_fixture_sanity_slots.nim

[Suite] Official - Sanity - Slots  [Preset: minimal]
stateRef.slot = 4
postRef.slot = 12
/mnt/sda3/storage/CODE/status/nim-beacon-chain-clean/tests/official/test_fixture_sanity_slots.nim(51) test_fixture_sanity_slots
/mnt/sda3/storage/CODE/status/nim-beacon-chain-clean/tests/official/test_fixture_sanity_slots.nim(47) runTest
/mnt/sda3/storage/CODE/status/nim-beacon-chain-clean/tests/helpers/debug_state.nim(51) testImpl_slots_identifier
/mnt/sda3/storage/CODE/status/nim-beacon-chain-clean/vendor/nimbus-build-system/vendor/Nim/lib/system/assertions.nim(29) failedAssertImpl
/mnt/sda3/storage/CODE/status/nim-beacon-chain-clean/vendor/nimbus-build-system/vendor/Nim/lib/system/assertions.nim(22) raiseAssert
/mnt/sda3/storage/CODE/status/nim-beacon-chain-clean/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(49) sysFatal

    Unhandled exception: /mnt/sda3/storage/CODE/status/nim-beacon-chain-clean/tests/helpers/debug_state.nim(51, 13) `stateRef.slot == postRef.slot` 
Diff: stateRef.slot = 18446743592673214469
and   postRef.slot = 12
 [AssertionError]
[FAILED] Slots - over_epoch_boundary
```

**Pull request merged**
