### PR TITLE
Fix: minor typo

### PR DESCRIPTION
**Pull request by omahs**
Fix: minor typo

### CODE REVIEW

**Comment by tersec** [comment]
Indeed, but it should target the `unstable` branch to be merged.

**Comment by omahs** [comment]
@tersec the branch is changed, happy new year! 🌟

**Comment by tersec** [comment]
@omahs happy new year, as well.

Also, 
2023-01-01-145459_915x909_scrot

after the rebasing, it now reverts some changes that had been in `unstable` but not in `stable`. It changes files `.github/workflows/release.yml` and `docker/dist/binaries/Dockerfile.bn.{amd64,arm,arm64}`.

**Comment by omahs** [comment]
@tersec I'll close this one and start fresh to avoid this issue

**Pull request closed without merging**
