### PR TITLE
Bump nim-eth to use lrucache for discovery sessions

### PR DESCRIPTION
**Pull request by kdeme**
See also https://github.com/status-im/nim-eth/issues/242

### CODE REVIEW

**Comment by arnetheduck** [comment]
how will this interact with storing known peers in database to reconnect to them on restart?

**Comment by kdeme** [comment]
> how will this interact with storing known peers in database to reconnect to them on restart?

It won't. When communicating with stored peers after a restart one will still need to handshake and store a new session for each peer. Sessions are supposed to be ephemeral, and thus in memory only.
 
When adding a persistent store of peers to seed from at restart, it is likely a metric like liveness would be used for deciding on which peer gets stored. I guess the only link is that peers with good "liveness" are likely to have also session stored in the lrucache due to recent/often communication. Relevant issue: https://github.com/status-im/nim-eth/issues/189

**Comment by kdeme** [comment]
By the way, is that Jenkins (finalization) failure something that still occasionally occurs? Or really relevant to the changes of the PR...?

**Comment by tersec** [comment]
Depends on which what went wrong. https://ci.status.im/job/nimbus/job/nim-beacon-chain/job/multibranch/job/discv5-lrucache/1/display/redirect is a 404 for me, so I can't tell.

**Review by arnetheduck — APPROVED** [review]

**Pull request merged**
