### PR TITLE
Transfer - split process_transfer/processTransfers + tests + fixes

### PR DESCRIPTION
**Pull request by mratsim**

### CODE REVIEW

**Comment by mratsim** [comment]
Same failures on Windows x64 as #408, it works on 32-bit

https://ci.appveyor.com/project/nimbus/nim-beacon-chain/builds/27293393/job/0b600abqo06snpgi#L3130

```
[Suite] Official - Operations - Transfers  [Preset: minimal]
  [OK] [Valid]   success_non_activated
  [OK] [Valid]   success_withdrawable
  [OK] [Valid]   success_active_above_max_effective
  [OK] [Valid]   success_active_above_max_effective_fee
NOT 2019-09-09 23:14:47+00:00 Transfer: incorrect signature              tid=2716
  [OK] [Invalid] invalid_signature
NOT 2019-09-09 23:14:47+00:00 Transfer: only senders who either 1) have never been eligible for activation or 2) are withdrawable or 3) have a balance of MAX_EFFECTIVE_BALANCE after the transfer are valid. tid=2716
  [OK] [Invalid] active_but_transfer_past_effective_balance
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] incorrect_slot
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Valid]   transfer_clean
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Valid]   transfer_clean_split_to_fee
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] insufficient_balance_for_fee
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] insufficient_balance_for_amount_result_full
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] insufficient_balance_for_combined_result_dust
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] insufficient_balance_for_combined_result_full
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] insufficient_balance_for_combined_big_amount
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] insufficient_balance_for_combined_big_fee
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] insufficient_balance_off_by_1_fee
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] insufficient_balance_off_by_1_amount
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] insufficient_balance_duplicate_as_fee_and_amount
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] no_dust_sender
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] no_dust_recipient
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] non_existent_sender
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] non_existent_recipient
    Unhandled exception: The parameter is incorrect.
 [OSError]
  [FAILED] [Invalid] invalid_pubkey
```

**Comment by mratsim** [comment]
Yes I don't want to merge yet, I'll debug it on my main computer.

**Comment by tersec** [comment]
I'd be happy to merge this with something akin to https://github.com/status-im/nim-beacon-chain/pull/438 included either as part of the initial merge or after the fact.

**Comment by mratsim** [comment]
let's merge this.

**Comment by tersec** [comment]
Ah, I see it's only failing because proposer slashing's now breaking for the same reason. LGTM.

**Pull request merged**
