### PR TITLE
Migrate the Keystore to nim-json-serialization (WIP branch from Zed)

### PR DESCRIPTION
**Pull request by zah**

### CODE REVIEW

**Comment by zedeus** [comment]
This is using the wrong commit, not sure what happened. Note the serialization change at line 210
https://github.com/zedeus/nim-beacon-chain/commit/76d5c894869a2f861a8a10cae4da34118b131e4e

**Comment by zah** [comment]
Maybe I did something wrong while rebasing. Can you push a quick fixup?

**Comment by zedeus** [comment]
I created a new branch based on devel, you can remake this branch or reset then pull from mine

**Comment by arnetheduck** [comment]
so this branch is obsolete?

**Comment by zah** [comment]
No, this branch needs a new feature in nim-json-serialization before it can be completed.
The feature is not optional, because it's also required for turning some possible `FieldError` defects during deserialization into recoverable errors.

**Comment by zah** [comment]
Superseded by https://github.com/status-im/nim-beacon-chain/pull/1390/commits/658e85cbeb1f167fba6f42ed889eb4989912aaf7

**Pull request closed without merging**
