### PR TITLE
remove UnusedImport spam

### PR DESCRIPTION
**Pull request by tersec**
Tested with `LOG_LEVEL=TRACE`.

The only change outside the `tests/` directory is removing imports from `beacon_chain/spec/beaconstate.nim` and `beacon_chain/spec/crypto.nim`.

### CODE REVIEW

**Comment by tersec** [comment]
The `continuous-integration/travis-ci/push` failure is spurious; 2 of 3 work, and the one which doesn't is:
```
$ export GIT_LFS_SKIP_SMUDGE=1

21.34s$ git clone --depth=10 --branch=het https://github.com/status-im/nim-beacon-chain.git status-im/nim-beacon-chain

Cloning into 'status-im/nim-beacon-chain'...

fatal: unable to access 'https://github.com/status-im/nim-beacon-chain.git/': Could not resolve host: github.com

The command "eval git clone --depth=10 --branch=het https://github.com/status-im/nim-beacon-chain.git status-im/nim-beacon-chain " failed. Retrying, 2 of 3.

Cloning into 'status-im/nim-beacon-chain'...

fatal: unable to access 'https://github.com/status-im/nim-beacon-chain.git/': Could not resolve host: github.com

The command "eval git clone --depth=10 --branch=het https://github.com/status-im/nim-beacon-chain.git status-im/nim-beacon-chain " failed. Retrying, 3 of 3.
```

**Comment by jangko** [comment]
I just can't help not to comment about module level `{.used.}` pragma. in nimbus repo there is a module imported by two other module. one of them need it inside generic proc(therefore the compiler complains about unused import), the other one not need it at all. using `{.used.}` pragma make both of them silence. 
I think we should request new feature: `import modulename {.used.}` rather than module level `{.used.}`

**Comment by mratsim** [comment]
It might have been fixed last week: https://github.com/nim-lang/Nim/issues/11826

cc @Araq

**Comment by mratsim** [comment]
The build failure is Travis not being able to clone the github repo on ARM: https://travis-ci.org/status-im/nim-beacon-chain/jobs/611756302?utm_medium=notification&utm_source=github_status

Merging

**Comment by jangko** [comment]
> It might have been fixed last week: nim-lang/Nim#11826

ah, not bad, a progress. although it will silence every unused imports, legit or not.

**Pull request merged**
