### PR TITLE
Revert "stop testing broken upstream version-2-0"

### PR DESCRIPTION
**Pull request by arnetheduck**
Reverts status-im/nimbus-eth2#6499

### CODE REVIEW

**Comment by arnetheduck** [comment]
https://github.com/nim-lang/Nim/issues/24002

**Comment by tersec** [comment]
No objections to merging this once the issue is resolved

**Comment by arnetheduck** [comment]
so per the comments in the PR, this is actually a latent bug in our code exposed by additional strictness - ie the template never worked as intended basically, and prints `None` in the logs.

**Comment by tersec** [comment]
In which case, fixing that code in `nimbus-eth2` works also

**Comment by arnetheduck** [comment]
seems to work

**Pull request merged**
