### PR TITLE
bump submodules

### PR DESCRIPTION
**Pull request by stefantalpalaru**

### CODE REVIEW

**Comment by zah** [comment]
I'm having a lot of trouble in my git setup with rebasing over these submodule bumps. git will sometimes enter a state where it becomes impossible to resolve a confict by executing `git add vendor/foo`. Is anyone else experiencing the same problem?

**Comment by stefantalpalaru** [comment]
How and why are you rebasing?

**Comment by zah** [comment]
I'm rebasing branches of in-flight PRs. If the PR needs to bump a sub-module, it will conflict with a merged trivial bump like this one. This would be fine if resolving the conflict was trivial, but my git breaks down at this point for some reason and refuses to get the submodule out of the "conflicted" state. 

When this happens, the solution I've been using is to edit the history of my local branch with `git rebase -i` in such a way that removes or harmonizes the conflicting submodule bumps and to potentially reapply them at the end (which is a bit bad for producing correct builds in the intermediate commits).

**Comment by stefantalpalaru** [comment]
Maybe the problem appears when the same submodule is pointing at different commits in the two branches?

These SO comments suggest using "git reset" after a merge conflict: https://stackoverflow.com/questions/826715/how-do-i-manage-conflicts-with-git-submodules

I guess the newer "git restore" should also work. Worth trying.

**Comment by arnetheduck** [comment]
odd - works for me:

```
[arnetheduck@tempus nim-beacon-chain]$ git rebase origin/devel 
Failed to merge submodule vendor/nim-libp2p (merge following commits not found)
Auto-merging vendor/nim-libp2p
CONFLICT (submodule): Merge conflict in vendor/nim-libp2p
Auto-merging beacon_chain/inspector.nim
error: could not apply 0ec07ec6... show peer info on connect
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 0ec07ec6... show peer info on connect
[arnetheduck@tempus nim-beacon-chain]$ git st
interactive rebase in progress; onto ce897fe
Last command done (1 command done):
   pick 0ec07ec show peer info on connect
No commands remaining.
You are currently rebasing branch 'peerinfo' on 'ce897fe'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   beacon_chain/eth2_network.nim
	modified:   beacon_chain/inspector.nim
	modified:   beacon_chain/sync_protocol.nim
	modified:   beacon_chain/sync_protocol.nim.generated.nim

Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add <file>..." to mark resolution)
	both modified:   vendor/nim-libp2p

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   vendor/nim-eth (new commits)
	modified:   vendor/nim-eth2-scenarios (new commits)
	modified:   vendor/nim-json-rpc (new commits)
	modified:   vendor/nim-stew (new commits)

[arnetheduck@tempus nim-beacon-chain]$ cd vendor/nim-libp2p/
[arnetheduck@tempus nim-libp2p]$ git checkout master 
Already on 'master'
Your branch is up to date with 'origin/master'.
[arnetheduck@tempus vendor]$ git add nim-libp2p
[arnetheduck@tempus vendor]$ git st
interactive rebase in progress; onto ce897fe
Last command done (1 command done):
   pick 0ec07ec show peer info on connect
No commands remaining.
You are currently rebasing branch 'peerinfo' on 'ce897fe'.
  (all conflicts fixed: run "git rebase --continue")

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   ../beacon_chain/eth2_network.nim
	modified:   ../beacon_chain/inspector.nim
	modified:   ../beacon_chain/sync_protocol.nim
	modified:   ../beacon_chain/sync_protocol.nim.generated.nim
	modified:   nim-libp2p

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   nim-eth (new commits)
	modified:   nim-eth2-scenarios (new commits)
	modified:   nim-json-rpc (new commits)
	modified:   nim-stew (new commits)

[arnetheduck@tempus vendor]$ git submodule update 
Submodule path 'nim-eth': checked out 'be9a87848e068d68aa8fa1a7bfa07d7c7271eba7'
Submodule path 'nim-eth2-scenarios': checked out '3a8b4dacd08814d0afa6731ea53cc282b78c6854'
Submodule path 'nim-json-rpc': checked out '271512c161706e08533690fdc8bbbbc54f1dc0ed'
Submodule path 'nim-stew': checked out 'cf82e2d51d12c3ca461cb170c2a4e2eada3bfe67'
[arnetheduck@tempus vendor]$ git st
interactive rebase in progress; onto ce897fe
Last command done (1 command done):
   pick 0ec07ec show peer info on connect
No commands remaining.
You are currently rebasing branch 'peerinfo' on 'ce897fe'.
  (all conflicts fixed: run "git rebase --continue")

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   ../beacon_chain/eth2_network.nim
	modified:   ../beacon_chain/inspector.nim
	modified:   ../beacon_chain/sync_protocol.nim
	modified:   ../beacon_chain/sync_protocol.nim.generated.nim
	modified:   nim-libp2p
[arnetheduck@tempus vendor]$ git rebase --continue 
[detached HEAD 8fd4fec] show peer info on connect
 5 files changed, 18 insertions(+), 23 deletions(-)
Successfully rebased and updated refs/heads/peerinfo.
```

**Pull request merged**
