### PR TITLE
bump `nim-zlib` to `f34ca261efd90f118dc1647beefd2f7a69b05d93`

### PR DESCRIPTION
**Pull request by etan-status**
- ignore *.exe
- nim 1.6 adjustment
- update github action to v3
- use Nim 2.0 in CI
- test both refc and ORC in post-1.6 Nim versions
- remove Nim 1.2 and 1.4 support

### CODE REVIEW

**Comment by etan-status** [comment]
Needed for `nim-websock` bump.

Otherwise:

```
Error: type mismatch: got 'ptr uint8' for 'cast[ptr uint8](unsafeAddr(data[0]))' but expected 'ptr cuchar'
```

**Comment by etan-status** [comment]
Requires https://github.com/status-im/nimbus-eth2/pull/5097 first, and subsequently, another separate `nim-websock` bump for compatibility with the zlib bump.

**Comment by arnetheduck** [comment]
> Requires https://github.com/status-im/nimbus-eth2/pull/5097 first, and subsequently, another separate nim-websock bump for compatibility with the zlib bump.

just put both in the same PR? ie that documents their codependency

**Comment by etan-status** [comment]
Yes, hence why doing the #5097 separately. That one includes the parts that are not codependent.

**Pull request merged**
