### PR TITLE
More 0.7.1 updates

### PR DESCRIPTION
**Pull request by tersec**
- replace get_attestation_slot(...) with 0.7.1 get_attestation_data_slot(...) and update all callers
- update AttestationData to be almost 0.7.1, except nonextistent slot field
- update Crosslink and get_winning_crosslink_and_attesting_indices(...) to 0.7.1

### CODE REVIEW

**Comment by tersec** [comment]
> There is a ambiguous acall on windows:
> 
> ```
>         ... Hint: helpers [Processing]
>         ... Hint: validator [Processing]
>         ... Hint: state_transition [Processing]
>         ... Hint: fork_choice [Processing]
>         ... Hint: attestation_pool [Processing]
>         ... Hint: block_pool [Processing]
>         ... Hint: validator_pool [Processing]
>         ... Hint: trusted_state_snapshots [Processing]
>         ... Hint: sync_protocol [Processing]
>         ... Hint: bitranges [Processing]
>         ... Hint: request_manager [Processing]
>         ... beacon_node.nim(695, 43) Error: ambiguous call; both os_shims.getCurrentProcessId()[declared in ..\..\..\Users\appveyor\.nimble\pkgs\std_shims-0.1.0\std_shims\os_shims.nim(10, 7)] and daemonapi.getCurrentProcessId()[declared in ..\..\..\Users\appveyor\AppData\Local\Temp\1\nimble_2584\githubcom_statusimnimlibp2p\libp2p\daemon\daemonapi.nim(530, 7)] match for: ()
> ```
> 
> https://ci.appveyor.com/project/nimbus/nim-beacon-chain/builds/25507340/job/u0nc6bt7kmq9glt4#L592

Yes, I know, that's why I set up https://github.com/status-im/nim-beacon-chain/pull/298 to show that these were happening notwithstanding any code changes here. They're upstream in `nim-beacon-chain` master.

I've asked @zah and he's asked @stefantalpalaru about it.

**Comment by mratsim** [comment]
retriggering following https://github.com/status-im/nim-libp2p/pull/24

**Comment by tersec** [comment]
The rebuild addresses the 64-bit build issues, but 32-bit build issues remain:
```
        ... eth2_network.nim(167, 17) Error: type mismatch: got <type MultiAddress, IpAddress, int literal(6), Port>
        ... but expected one of:
...
        ... expression: init(MultiAddress, globalListeningAddr, IPPROTO_TCP, Port(conf.tcpPort))
```

**Comment by tersec** [comment]
It seems clear this is now a 32-bit Windows (or 32-bit AppVeyor, either way) specific issue, so going to just merge this.

**Pull request merged**
