### PR TITLE
Rework pubsub

### PR DESCRIPTION
**Pull request by dryajov**
This consumes the split out pubsub from https://github.com/status-im/nim-libp2p/pull/322, most things work and it's a big improvement over past versions. Please give it a try.

### CODE REVIEW

**Comment by tersec** [comment]
This is apparently not rebased to current `devel` -- it contains several commits on `devel`, e.g., https://github.com/status-im/nim-beacon-chain/pull/1474/commits/e86e61dc2a0d1a93fc41484700c29301cc07015d ?

**Comment by stefantalpalaru** [comment]
You also need a nim-stew bump.

**Comment by stefantalpalaru** [comment]
There's a drastic improvement in the libp2p stream (and associated futures) leaks.
Here are two 50-minutes Medalla runs while doing backward sync. The first one is this branch, "rework-pubsub", and the second is "devel":
img

**Comment by zah** [comment]
Merged here:
https://github.com/status-im/nim-beacon-chain/pull/1511

**Pull request closed without merging**
