### PR TITLE
Fix libp2p hash

### PR DESCRIPTION
**Pull request by sinkingsugar**
Auto bump was targeting unstable, introducing wrong changes into nimbus.
I made a separate draft unstable auto bump.
This PR fixes nimbus to use current master.

### CODE REVIEW

**Comment by tersec** [comment]
I don't understand "Auto bump was targeting unstable, introducing wrong changes into nimbus."?

**Comment by sinkingsugar** [comment]
> I don't understand "Auto bump was targeting unstable, introducing wrong changes into nimbus."?

unstable of libp2p, while it should target master of libp2p

**Comment by tersec** [comment]
Caught this happening with a lot more details: https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnimbus-eth2%2Fprs/detail/PR-2416/6/pipeline

It works fine on macOS, not Linux. I modified the Jenkins build script's `Build` step:
```
stage("Build") {
    sh """#!/bin/bash
    set -e
    # to allow the following parallel stages
    pwd
    cat config.nims
    ./env.sh nim --version
    ./env.sh nim --warnings:list || true
    make -j${env.NPROC} QUICK_AND_DIRTY_COMPILER=1 deps
    ./scripts/setup_official_tests.sh jsonTestsCache
    """
}
```
and https://ci.status.im/blue/rest/organizations/jenkins/pipelines/nimbus/pipelines/nimbus-eth2/pipelines/prs/branches/PR-2416/runs/6/nodes/7/log/?start=0
shows `pwd` is
```
/home/jenkins/workspace/nimbus_nimbus-eth2_prs_PR-2416
```
`config.nims` is what is should be.

`nim --version` is
```
Nim Compiler Version 0.20.0 [Linux: amd64]
Compiled at 2019-06-05
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: be9c38d2659496f918fb39e129b9b5b055eafd88
active boot switches: -d:release
```
Which, well.

And as a result, the warnings don't include `ObservableStores`:
```
Warnings:
  [x] CannotOpenFile
  [x] OctalEscape
  [x] XIsNeverRead
  [x] XmightNotBeenInit
  [x] Deprecated
  [x] ConfigDeprecated
  [x] SmallLshouldNotBeUsed
  [x] UnknownMagic
  [x] RedefinitionOfLabel
  [x] UnknownSubstitutionX
  [x] LanguageXNotSupported
  [x] FieldXNotSupported
  [x] CommentXIgnored
  [x] TypelessParam
  [x] UseBase
  [x] WriteToForeignHeap
  [x] UnsafeCode
  [x] EachIdentIsTuple
  [x] ProveInit
  [ ] ProveField
  [ ] ProveIndex
  [ ] GcUnsafe
  [x] GcUnsafe2
  [ ] Uninit
  [x] GcMem
  [x] Destructor
  [x] LockLevel
  [x] ResultShadowed
  [x] Spacing
  [x] CaseTransition
  [x] User
```


The macOS build setup, by contrast, shows for Nim version and warnings supported (https://ci.status.im/blue/rest/organizations/jenkins/pipelines/nimbus/pipelines/nimbus-eth2/pipelines/prs/branches/PR-2416/runs/6/nodes/32/log/?start=0):
```
Nim Compiler Version 1.2.6 [MacOSX: amd64]
Compiled at 2021-03-16
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: f05ba3c667157f46f141ff700121c7aff86cf07a
active boot switches: -d:release
Warnings:
  [x] CannotOpenFile
  [x] OctalEscape
  [x] XIsNeverRead
  [x] XmightNotBeenInit
  [x] Deprecated
  [x] ConfigDeprecated
  [x] SmallLshouldNotBeUsed
  [x] UnknownMagic
  [x] RedefinitionOfLabel
  [x] UnknownSubstitutionX
  [x] LanguageXNotSupported
  [x] FieldXNotSupported
  [x] CommentXIgnored
  [x] TypelessParam
  [x] UseBase
  [x] WriteToForeignHeap
  [x] UnsafeCode
  [x] UnusedImport
  [x] InheritFromException
  [x] EachIdentIsTuple
  [x] UnsafeSetLen
  [x] UnsafeDefault
  [x] ProveInit
  [ ] ProveField
  [ ] ProveIndex
  [x] IndexCheck
  [ ] GcUnsafe
  [x] GcUnsafe2
  [ ] Uninit
  [x] GcMem
  [x] Destructor
  [x] LockLevel
  [x] ResultShadowed
  [x] Spacing
  [x] CaseTransition
  [x] CycleCreated
  [x] ObservableStores
  [x] User
```

As a result, the Linux, but not macOS, build fails with:
```
/home/jenkins/workspace/nimbus_nimbus-eth2_prs_PR-2416/config.nims(1, 2) Error: unknown warning: ObservableStores

/home/jenkins/workspace/nimbus_nimbus-eth2_prs_PR-2416/config.nims(1, 2) Error: unknown warning: ObservableStores
```
Because `config.nims` in `nimbus-eth2` (and nim-libp2p does basically the same thing slightly differently) disables said warning.

**Comment by tersec** [comment]
Doubling `maxCacheSize` during Jenkins replay from 250 to 500 made no discernible difference.

**Comment by sinkingsugar** [comment]
Why we use Nim ` 0.20.0 ` on linux?

**Comment by tersec** [comment]
We don't, at least not intentionally. It's likely because https://github.com/nim-lang/csources used to bootstrap Nim is 0.20, so it's using that somehow.

That just pushes the question a layer deeper, though. It seems likely there's some caching issue somewhere causing this, but at this point I'm uncertain.

**Comment by sinkingsugar** [comment]
Closing in favor of auto bump btw, which passed.

**Pull request closed without merging**
