### PR TITLE
bump a few submodules

### PR DESCRIPTION
**Pull request by stefantalpalaru**

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
The Jenkins macos-03 host has connectivity issues: https://github.com/status-im/infra-ci/issues/31

**Review by tersec — APPROVED** [review]

**Comment by arnetheduck** [comment]
odd because other builds are succeeding: https://github.com/status-im/nimbus-eth2/pull/2537

**Comment by stefantalpalaru** [comment]
> odd because other builds are succeeding: #2537

That one ran on a different host: macos-01 - https://ci.status.im/job/nimbus/job/nimbus-eth2/job/prs/job/PR-2537/2/consoleFull

There might be some hashing done to distribute builds between hosts, which means the same PR's CI jobs will always run on the same hosts.

**Comment by arnetheduck** [comment]
ok, so this should be mergeable?

**Comment by stefantalpalaru** [comment]
Yes, it's mergeable.

**Pull request merged**
