### PR TITLE
testnet finalisation testing in CI

### PR DESCRIPTION
**Pull request by stefantalpalaru**
The CI is expected to fail, for now. I'll comment out the failing command, after I make sure it fails the right way.

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
Commented out. It takes 4m44s on Jenkins. To be enabled when it passes for either testnet0 or testnet1.

**Comment by arnetheduck** [comment]
I don't think this will do what we expect it  to - connecting to testnet means that we start syncing with it, so this will only test syncing a little bit, if at all - ie basically the testnet is at time X when you your beacon node, then it starts syncing - what we want to test in ci for now is that if we launch a fresh testnet, it will attest and finalise to a certain point.

**Comment by arnetheduck** [comment]
another way to put this: to know if the testnet is finalizing, you have to look at what epoch it's at currently, and compare that with the epoch it last finalized - if "current_epoch - finalized_epoch > 4", you know it's broken.

@tersec perhaps that's a better way to express the command line option / check as well - ie that the finalization should never lag more than N epochs - of course, it's still a heuristic - in the real world we'll see splits and such causing longer non-finalizations, but our testnets are controlled to the degree that it should "never" happen.

**Comment by arnetheduck** [comment]
the option should perhaps allow setting `4` to something different as well

**Comment by stefantalpalaru** [comment]
> what we want to test in ci for now is that if we launch a fresh testnet, it will attest and finalise to a certain point

That is exactly what this CI test does. It launches 10 nodes (including the bootstrap node), telling them to stop at epoch 5, which is after the finalisation check kicks in for each one of the nodes, in epoch 4. It's the minimal finalisation proof that we need.

**Comment by tersec** [comment]
> the option should perhaps allow setting `4` to something different as well

Why?

**Comment by arnetheduck** [comment]
> Why?

because if the network is a bit unstable, it might take more than 4 to finalize.. ie it would be nice to run experiments where we kill half the nodes in the testnet, let an hour pass then restart them - the network should at that point "snap back"

**Comment by arnetheduck** [comment]
> That is exactly what this CI test does. 

ok, I guess I'm not clear about the difference between `launch_local_testnet` and `make eth2_network_sim` and `tests/simulation/start`

**Pull request merged**
