### PR TITLE
[RFC - Doc] State of Nimbus block & attestation flows

### PR DESCRIPTION
**Pull request by mratsim**
This PR outlines the current state of Nimbus architecture with regards to block and attestation processing

### Security

This paves the way to solve Trail of Bits recommendation of documenting the flow of untrusted data as it becomes validated and verified and also the associated buffers max size to ensure untrusted data cannot be used to take a Nimbus node out of mem: https://github.com/status-im/nimbus-eth2/issues/1597.

### Frame of reference

Now that most low hanging fruits are done, we need to expose more batching opportunities https://github.com/status-im/nimbus-eth2/issues/2339 and also prepare for the growing performance needs in HF1 and phase 1 that are just around the corner.

This should help to understand where and what we have now as so far the project as grown in an organic manner.

The goal is to make sure that for future performance, bottleneck and architecture discussions we can have all the same frame of reference.

### New joiners / auditors

This should also be very helpful to new joiners and auditors to understand the codebase.

## State

- [x] Block processing (input)
  - [x] Block validation 
  - [x] Module list, producers & consumers
    - [x] Function calls 
  - [x] Bottlenecks during sync
  - [x] Bottlenecks when synced
  - [x] Diagram 
- [x] Block processing (output)
  - [x] Gossip 
- [x] Attestation processing (input)
  - [x] Attestation validation 
  - [x] Module list, producers & consumers
    - [x] Function calls 
  - [x] Bottlenecks during sync
  - [x] Bottlenecks when synced
  - [x] Diagram 
- [x] Attestation processing (output)
  - [x] Attestation aggregation
  - [x] Gossip

### CODE REVIEW

**Comment by arnetheduck** [comment]
a point about the networking flow:

we receive blocks and attestations from a number of external / untrusted sources - all pass through eth2_processor which acts as a kind of load balancer and gatekeeper - from a security point of view, it's an important component because that's were the setup for the pre-checks are hosted - as such, the diagram (and of course the code) should funnel everything through it before it passes on to the other layers - there should be no flow from sync to chaindag for example afair

**Comment by mratsim** [comment]
> a point about the networking flow:
> 
> we receive blocks and attestations from a number of external / untrusted sources - all pass through eth2_processor which acts as a kind of load balancer and gatekeeper - from a security point of view, it's an important component because that's were the setup for the pre-checks are hosted - as such, the diagram (and of course the code) should funnel everything through it before it passes on to the other layers - there should be no flow from sync to chaindag for example afair

There is but in the `out` direction, i.e. peers ask us for blocks and the sync_protocol directly look into the chainDag

https://github.com/status-im/nimbus-eth2/blob/5f62a3938e6d8fc991f12085b2c87ed4638d4e7b/beacon_chain/sync_protocol.nim#L137-L157

I agree though that it would be clearer if we add `sync_in` and `sync_out` spelled out, maybe in filename.

**Comment by arnetheduck** [comment]
> There is

read-only, ie it shouldn't be a double-sided arrow

**Comment by mratsim** [comment]
> > There is
> 
> read-only, ie it shouldn't be a double-sided arrow

~~Unfortunately Graphviz is the limiting factor there. If I make it one-sided with the arrow in the ChainDag -> Sync_protocol direction, ChainDag will have to be above SyncProtocol and that will mess up everything as almost everything sits above ChainDag in that flow.~~

Scratch that, seems like there is a `[dir=back]` property.

**Comment by arnetheduck** [comment]
same goes for requestmanager/queue

**Comment by arnetheduck** [comment]
quarantine is also read from, just can't remember where :)

**Comment by mratsim** [comment]
> quarantine is also read from, just can't remember where :)

https://github.com/status-im/nimbus-eth2/blob/5f62a3938e6d8fc991f12085b2c87ed4638d4e7b/beacon_chain/nimbus_beacon_node.nim#L1057-L1066

**Comment by zah** [comment]
Personally, I find the prose much more useful than the diagrams and would like to see it expanded further. It already discusses to some extent the requirements, the rationales behind the design and the flow of information, but it does this in a bit ad-hoc fashion. It could probably be organized a bit better by first presenting the problems and then describing the solutions.

**Comment by mratsim** [comment]
> Personally, I find the prose much more useful than the diagrams and would like to see it expanded further. It already discusses to some extent the requirements, the rationales behind the design and the flow of information, but it does this in a bit ad-hoc fashion. It could probably be organized a bit better by first presenting the problems and then describing the solutions.

The problems/solutions is something we should create issues for or discuss in the architecture channel or maybe even organize a call on that.
I want the doc to be factual about what we have now.

I will reorg the doc by grouping more area that make sense in a folder if there is sufficient code that is written or will be written in a separate PR, for example:
- sync: sync_protocol, request_manager, the future weak_subjectivity_sync
- validators: slashing_protection, keystores, future doppelganger_detection refactorings
Also with specific code link instead of just the proc name which shoudl help navigate the codebase.

**Pull request merged**
