### PR TITLE
state/block_sim: make genesis caching opt-in

### PR DESCRIPTION
**Pull request by stefantalpalaru**
I got a local error after loading an old "genesim_minimal_2000.ssz" while running `make test`: https://gist.github.com/stefantalpalaru/8c542e6c7e28e7bd828cbf26b2b8898b

### CODE REVIEW

**Comment by tersec** [comment]
This is an artifact of the 0.11.3/0.12.1 spec split. It caches one spec's version of the genesis state by some mechanism (say, 'make test'), then tries to use another.

I wouldn't try to veto this PR, and I'm fine with how it addresses what it does, but it also doesn't solve any problem that I find particularly worthwhile. Once Altona fully takes over from Witti, we'll drop the dual-spec-version compatibility, and this issue will disappear. Until then, just use slightly different numbers of validators, since the caching filename's a function of that.

A real fix might have the state and block sims detect in a friendlier way this and similar conditions, but they're not for end-users, so that seems a low priority.

My main concern is just the permanent/indefinite addition of configuration complexity, however minor, to solve a very temporary issue that end-users shouldn't encounter.

**Comment by stefantalpalaru** [comment]
> This is an artifact of the 0.11.3/0.12.1 spec split.

Not exactly, since it doesn't appear when running "make test" on a clean working tree. You would need to have old *.ssz files lying around from a previous run a few weeks ago.

> we'll drop the dual-spec-version compatibility, and this issue will disappear

No, you'll still have to manually delete these *.ssz files whenever a new spec changes something in their structure. That may nudge developers away from running tests locally before creating a PR.

**Comment by arnetheduck** [comment]
> Until then, just use slightly different numbers of validators, since the caching filename's a function of that.

should probably include the spec version in the filename too (the things in the name are heuristics - a hash of the types that make up a beaconstate would work more reliably)

**Comment by arnetheduck** [comment]
3 more developer-friendly options (these apps get used during development but rarely otherwise:

* spec version in filename
* try loading, if it fails, generate (print message) new cache
* try loading , if it fails, print message that hints that removing the cache might help

**Comment by stefantalpalaru** [comment]
> try loading, if it fails, generate (print message) new cache

I like this one.

**Comment by stefantalpalaru** [comment]
Unfortunately, the assertion error happens in "research/state_sim.nim:97", long after the cache has been loaded on line 45.

Creating new cache files for new spec versions clutters the current dir and does not guarantee that breaking changes won't happen under the same version.

**Comment by tersec** [comment]
I'm okay with any of the three suggestions by @arnetheduck .

> Unfortunately, the assertion error happens in "research/state_sim.nim:97", long after the cache has been loaded on line 45.

Presumably, by line 45, a detectable condition is created. Also, this still allows the display-an-error approach, even if one localizes it to lines 97.
 
> Creating new cache files for new spec versions clutters the current dir and does not guarantee that breaking changes won't happen under the same version.

- There aren't that many spec releases - 3 in the last month: https://github.com/ethereum/eth2.0-specs/releases; and

- If this error occurs with genesis states from the same spec version, that's a genuine bug. On the beacon_node side, where there's by definition lots of untrustworthy/untrusted input, this kind of anti-defensive programming is counterproductive, but being that these aren't end-user tools, a bug of this sort shouldn't be just disappeared.

**Comment by stefantalpalaru** [comment]
@tersec, can we rely on this surviving the move from 2 supported specs at the same time, and on it being up to date with the current spec version?
```nim
const ETH2_SPEC* {.strdefine.} = "v0.11.3"
```

If not, any other way to get this and stick it in the file name?

**Comment by tersec** [comment]
> @tersec, can we rely on this surviving the move from 2 supported specs at the same time, and on it being up to date with the current spec version?
> 
> ```nim
> const ETH2_SPEC* {.strdefine.} = "v0.11.3"
> ```
> 
> If not, any other way to get this and stick it in the file name?

No, I'm removing `ETH2_SPEC` as soon as I can.

Use:
```
const
  SPEC_VERSION* =
    when ETH2_SPEC == "v0.12.1":
      "0.12.1"
    else:
      "0.11.3" ## \
  ## Spec version we're aiming to be compatible with, right now
```

**Comment by stefantalpalaru** [comment]
Looks fragile, since it requires manual updating in a part of code you won't normally look at when updating the spec.

**Comment by tersec** [comment]
> Looks fragile, since it requires manually updating a part of code you won't normally look at when updating the spec.

- It's no more fragile than `ETH2_SPEC` would be in that regard.

- I do, in fact, assiduously update it each time I do a spec update. It's true that it doesn't have an easily grep-able pattern that would otherwise pop out, and there's no functional/semantic dependency within the codebase, but I've been consistent about it.

- And, regardless, I take your point more generally that it's more manual than it should be, and arguably one should refactor:
https://github.com/status-im/nim-beacon-chain/blob/49e9167b2806b7d7c9498978058f44d4e9a62608/tests/official/fixtures_utils.nim#L42-L48
which does directly create such a dependency, into using such a constant. But the constant I'd use would probably be `SPEC_VERSION`.

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/pull/1189 directly ties `SPEC_VERSION` into the rest of the codebase.

**Pull request merged**
