### PR TITLE
remove vestiges of rocksdb

### PR DESCRIPTION
**Pull request by tersec**

### CODE REVIEW

**Comment by zah** [comment]
Turns out we cannot remove this, because it's used in the test suite of nim-eth. When you do `nimble test` in "vendor/nim-eth", you get an error due to `rocksdb` missing.

**Comment by tersec** [comment]
Should `nim-eth`'s test suite depend on `rocksdb`?

**Comment by arnetheduck** [comment]
right, I remember now that this was the reason I didn't remove it.. in theory, yes - the tests of nim-eth should depend on rocksdb but that's not something we can express in our build system easily - in practise, the easiest way to work on these libraries is from inside a checkout of `nim-beacon-chain` or nimbus inside the `env.sh`-provided dependency environment - there's no other way to have per-workspace dependencies in nim right now.

**Comment by arnetheduck** [comment]
in rust, they do conditional dependencies for this sort of stuff - for example, `nim-eth` for nimbus needs the rocksdb feature but nim-beacon-chain doesn't - there's no way to express this presently - a bad workaround is to create lots of tiny git repos but that's a nightmare to work with - `nim-serialization` does this to the detriment of the developer experience - apart from being onerous and unpleasant to work with, it's also broken because it doesn't track versions that work well with each other which the users of the library pay for. 

a lesser evil here might perhaps be to detect that rocksdb is missing and skip these tests, highlighting them as skipped - this way, if the tests are run from within the `nimbus` env (that uses rocksdb), they will get run - otherwise, they won't.

**Comment by tersec** [comment]
So if people want, I can put this submodule back, but I do see:
> a lesser evil here might perhaps be to detect that rocksdb is missing and skip these tests, highlighting them as skipped - this way, if the tests are run from within the nimbus env (that uses rocksdb), they will get run - otherwise, they won't.

From a whole-Nimbus-project perspective. Having `nim-beacon-chain` carry dependencies which aren't actually for it, for what should be a project that's depended on but does not (conceptually, functionally) depend on `nim-beacon-chain` in terms of how different abstraction layers relate, because of limitations of `nimble` seems less than ideal.

**Comment by zah** [comment]
I think we should add back the sub-module as the easiest solution right now. We can revisit this once we start using the lockfile support in Nimble. I've taken some steps to do this here:

https://github.com/status-im/nim-beacon-chain/pull/829

**Comment by tersec** [comment]
> I think we should add back the sub-module as the easiest solution right now. We can revisit this once we start using the lockfile support in Nimble. I've taken some steps to do this here:
> 
> #829

I'm okay with that. Not my preferred approach, but I don't disagree with it enough to attempt to hinder it.

**Pull request merged**
