### PR TITLE
disable conditionality of warning disabling

### PR DESCRIPTION
**Pull request by tersec**
`nimbus-eth2` doesn't support earlier Nim versions anymore.

### CODE REVIEW

**Comment by arnetheduck** [comment]
> nimbus-eth2 doesn't support earlier Nim versions anymore.

this should be expressed in its nimble file

**Comment by tersec** [comment]
> > nimbus-eth2 doesn't support earlier Nim versions anymore.
> 
> this should be expressed in its nimble file

https://github.com/status-im/nimbus-eth2/pull/4908/commits/73c9c1957daff5ffbc1f7a9c9f6368757ca761b7

**Review by arnetheduck — APPROVED** [review]

**Comment by tersec** [comment]
https://ci.status.im/job/nimbus-eth2/job/platforms/job/macos/job/x86_64/job/PR-4908/3/display/redirect CI failure is unrelated.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/4909 disables that failure mode.

**Pull request merged**
