### PR TITLE
fix: gnosis build

### PR DESCRIPTION
**Pull request by filoozom**
I tried to build an executable for Gnosis with the following command:
```bash
make -j$(nproc) \
	LOG_LEVEL="TRACE" \
	NIMFLAGS="${NIMFLAGS_COMMON}" \
	PARTIAL_STATIC_LINKING=1 \
	QUICK_AND_DIRTY_COMPILER=1 \
	gnosis-chain-build
```

However, I got a few issues, including:
- `blockNumber` not existing in `DepositTreeSnapshot`
- `network` not being defined in a Gnosis-specific block
- `genesisState` being reassigned
- `deposit_contract_block_hash.txt` missing

I've never written `nim` before, so please consider these very rough and basic fixes. With these fixes, the code compiles, but I haven't tried running it yet.

### CODE REVIEW

**Comment by arnetheduck** [comment]
Hey, thanks for the PR! Do have a look at the `unstable` branch, there are several significant fixes to the gnosis build committed there already - I believe they cover what you've changed here but additional testing would be welcome!

**Comment by filoozom** [comment]
> Hey, thanks for the PR! Do have a look at the `unstable` branch, there are several significant fixes to the gnosis build committed there already - I believe they cover what you've changed here but additional testing would be welcome!

Ah, that's good to know! 😅 I'll have a look at that branch and get back to you 🙂

**Comment by filoozom** [comment]
@zah I see you're working on the Gnosis part, could I ask for the Chiado configs to be added as well? They were just merged from your PR (https://github.com/gnosischain/configs/pull/5). I'm syncing a node from scratch on mainnet now, and would like to do the same for Chiado and spin up a few validators to do some testing.

I'm happy to open a PR, but it would likely not be optimal given my lack of nim knowledge.

Also, would it be possible to work towards having CI builds for Gnosis binaries like for mainnet?

Thanks!

**Comment by arnetheduck** [comment]
@filoozom if you have a directory with the network config (genesis.ssz etc), you can launch the gnosis binary from unstable with `--network=/path/to/chiado` and it should "just work"

**Comment by arnetheduck** [comment]
@filoozom How goes the testing? Have you run into any other issues?

**Comment by filoozom** [comment]
@arnetheduck Hey! So I've tried 3 syncs, out of which 2 were full syncs. The first full sync (started `2023-01-13 16:56:34.010+00:00`) is still chugging along nicely:
```
INF 2023-01-18 09:27:40.023+00:00 Slot start                                 topics="beacnde" slot=7008144 epoch=438009 sync="01d12h22m (75.54%) 13.0865slots/s (DQQQDDDDPQ:5294159)" peers=28 head=988ab4c4:5294186 finalized=330884:736cc6a5 delay=23ms879us837ns
INF 2023-01-18 09:27:40.061+00:00 Slot end                                   topics="beacnde" slot=7008144 nextActionWait=n/a nextAttestationSlot=-1 nextProposalSlot=-1 syncCommitteeDuties=none head=988ab4c4:5294186
```

The second one had a less fortunate fate. It got stuck at ~33.66%, and didn't log anything to console for 4 hours, after which I restarted it and it [logged this](https://github.com/status-im/nimbus-eth2/files/10444264/nimbus-full-sync-stuck.log), before hanging indefinitely again (including no debug logs).

The snapshot synced one is working perfectly with both Nethermind and Erigon on my side. However, it's not backfilling all the blocks since genesis, is that normal? Or at least the final database size is only ~630MB when the node at 75% is already at 94+GB.

**Comment by zah** [comment]
All issues addressed in https://github.com/status-im/nimbus-eth2/pull/4460

**Comment by arnetheduck** [comment]
>  However, it's not backfilling all the blocks since genesis, is that normal? 

Yes, since the latest release, the nimbus client follows the protocol and downloads only the last 5 months of block data - the plan is that whoever needs to archive deep history should use [era files](https://nimbus.guide/era-store.html) - I'm happy to go over the process with anyone interested at gnosis such that you folks can publish your own era files (similar to how you provide checkpoints) - these would serve as "cold storage" for the gnosis consensus history

**Comment by arnetheduck** [comment]
> The second one had a less fortunate fate. 

this is likely due to a ttd problem that's been fixed in latest unstable as of today.

**Comment by filoozom** [comment]
Ah, I'd be very interested in the era files, sounds quite important! Do the nodes also prune from time to time to only keep the latest 5 months of history? If not, is there a way to trigger such a process manually?

**Comment by arnetheduck** [comment]
> If not, is there a way to trigger such a process manually?

Yes, this is also part of the upcoming release: https://github.com/status-im/nimbus-eth2/pull/4445 - it will eventually be default, once there are era files to cover - the process to get era files is to run a sync-from-genesis nimbus node then run a cron job that exports to era daily - the era files can then be served from a regular http server and used for deep archive purposes.

**Comment by filoozom** [comment]
Awesome, great to hear about all those features! It seems like there's never going to be an issue with the consensus layer taking too much disk space... 🙂 

Restarting a new sync with the TTD fix (I rebuilt a new version like one hour before it was pushed to `unstable` 😅), I'll keep you posted.

**Comment by filoozom** [comment]
Hey, so I played a bit with the era files, and managed to build `ncli_db` for Gnosis and then do an initial export. However, once that's done, subsequent runs only seem to export era files with an even id:
```
[...]
DBG 2023-01-21 14:45:33.506+00:00 Era file already exists                    tid=1 file=ncli_db.nim:531 era=854 name=gnosis-00854-7ccca1fe.era
DBG 2023-01-21 14:45:33.506+00:00 Era file already exists                    tid=1 file=ncli_db.nim:531 era=856 name=gnosis-00856-8850741a.era
DBG 2023-01-21 14:45:33.506+00:00 Era file already exists                    tid=1 file=ncli_db.nim:531 era=858 name=gnosis-00858-0d8ad287.era
DBG 2023-01-21 14:45:33.506+00:00 Era file already exists                    tid=1 file=ncli_db.nim:531 era=860 name=gnosis-00860-b7533d99.era
DBG 2023-01-21 14:45:33.507+00:00 UpdateStateData cache miss                 topics="chaindag" tid=1 file=blockchain_dag.nim:1455 current=e655429c:7063798 target=f808c01f:7061504
INF 2023-01-21 14:45:33.766+00:00 State replayed                             topics="chaindag" tid=1 file=blockchain_dag.nim:1541 blocks=1 slots=0 current=e655429c:7063798 ancestor=4c7b9aa5:7061503@7061504 target=f808c01f:7061504 ancestorStateRoot=b9f3d009 targetStateRoot=9cd81eaa found=false assignDur=166ms345us409ns replayDur=92ms748us617ns
INF 2023-01-21 14:45:33.766+00:00 Writing                                    tid=1 file=ncli_db.nim:557 name=gnosis-00862-d152c34d.era
NOT 2023-01-21 14:45:38.043+00:00 Written all complete eras                  tid=1 file=ncli_db.nim:519 era=863 endSlot=7069696 head=e655429c:7063798
All time are ms
     Average,       StdDev,          Min,          Max,      Samples,         Test
     137.678,        0.000,      137.678,      137.678,            1, tState
     388.668,        0.000,      388.668,      388.668,            1, tBlocks
```
When re-running:
```
[...]
DBG 2023-01-21 14:47:59.087+00:00 Era file already exists                    tid=1 file=ncli_db.nim:531 era=860 name=gnosis-00860-b7533d99.era
DBG 2023-01-21 14:47:59.087+00:00 Era file already exists                    tid=1 file=ncli_db.nim:531 era=862 name=gnosis-00862-d152c34d.era
NOT 2023-01-21 14:47:59.087+00:00 Written all complete eras                  tid=1 file=ncli_db.nim:519 era=864 endSlot=7077888 head=159af3a5:7063827
All time are ms
     Average,       StdDev,          Min,          Max,      Samples,         Test
       0.000,        0.000,        0.000,        0.000,            0, tState
       0.000,        0.000,        0.000,        0.000,            0, tBlocks
```
And the `861` file is indeed missing on the filesystem:
```
ls -al ./era/gnosis-0086*
-rw-r--r--    1 1000     1000     135071776 Jan 20 21:56 /media/gnosis/nimbus/era/gnosis-00860-b7533d99.era
-rw-r--r--    1 1000     1000     136733618 Jan 21 15:45 /media/gnosis/nimbus/era/gnosis-00862-d152c34d.era
```
However, when specifying `--era:861` it does generate the file:
```
INF 2023-01-21 14:49:09.570+00:00 Block DAG initialized                      tid=1 file=blockchain_dag.nim:1168 head=05db9052:7063841 finalizedHead=2a98af68:7063808 tail=23564cd1:0 backfill="(0, \"00000000\")" loadDur=2ms304us565ns summariesDur=263ms786us681ns finalizedDur=538ms581us903ns frontfillDur=128ns keysDur=306us253ns
DBG 2023-01-21 14:49:09.794+00:00 UpdateStateData cache miss                 topics="chaindag" tid=1 file=blockchain_dag.nim:1455 current=05db9052:7063841 target=ed8f3407:7053312
DBG 2023-01-21 14:49:09.933+00:00 State replayed                             topics="chaindag" tid=1 file=blockchain_dag.nim:1553 blocks=1 slots=0 current=05db9052:7063841 ancestor=1b41f6d9:7053311@7053312 target=ed8f3407:7053312 ancestorStateRoot=1681e1d7 targetStateRoot=4d9b926f found=false assignDur=48ms542us230ns replayDur=91ms213us54ns
INF 2023-01-21 14:49:09.934+00:00 Writing                                    tid=1 file=ncli_db.nim:557 name=gnosis-00861-ed1a7782.era
DBG 2023-01-21 14:49:13.367+00:00 Era file already exists                    tid=1 file=ncli_db.nim:531 era=862 name=gnosis-00862-d152c34d.era
NOT 2023-01-21 14:49:13.367+00:00 Written all complete eras                  tid=1 file=ncli_db.nim:519 era=864 endSlot=7077888 head=05db9052:7063841
All time are ms
     Average,       StdDev,          Min,          Max,      Samples,         Test
     131.003,        0.000,      131.003,      131.003,            1, tState
     368.446,        0.000,      368.446,      368.446,            1, tBlocks
```
Is this something expected? I don't see why even numbered era files would be enough, but I might be missing something?

Also, the manually re-generated `861` file is exactly the same as is generated when doing a full re-export.

By the way, if there's a better way to talk about this than here, maybe it would be better to move? Do you have a Discord server maybe?

**Comment by arnetheduck** [comment]
discord: https://discord.gg/9dWwPnG

probably, your build of gnosis didn't use the gnosis network parameters, ie building ncli_db for gnosis specifically needs the same flags as the gnosis build of the beacon node (see makefile) and `--network:gnosis` when running.

**Comment by filoozom** [comment]
I built it with `make -j$(nproc) ncli_db NIM_PARAMS="-d:gnosisChainBinary -d:const_preset=gnosis"`, which seems to work but might not be exactly right because the logs don't look the same, I guess some `NIM_PARAMS` are getting overridden or something?

I also re-ran with `--network gnosis`. I don't see why it would have fixed anything (and don't use it when running a node normally), but I removed the `86*` files, re-ran the command an it now seems to be working. Thanks!

**Pull request closed without merging**
