### PR TITLE
remove removed Debug/getDebugChainHeads V1

### PR DESCRIPTION
**Pull request by tersec**
https://github.com/ethereum/beacon-APIs/pull/319

### CODE REVIEW

**Comment by zah** [comment]
Previously, we've discussed that the best possible way to remove deprecated endpoints is to replace their implementation with an informative error message.

**Comment by tersec** [comment]
> Previously, we've discussed that the best possible way to remove deprecated endpoints is to replace their implementation with an informative error message.

Considered that. This is in the debug namespace. While that's been abused for useful things such as `getState`, which probably shouldn't have been in this namespace to begin with, in general, trying to comply with more usual the meaning of that as, actually being a commitment to something "less" than the beacon/validator/etc namespaces (otherwise, what's the point).

That's kind of the deal with these namespaces: easier to add, easier to change, easier to remove.

So don't strongly oppose it in this case, but it's not the default I'd go with for the debug namespace.

**Comment by zah** [comment]
It's very cheap to add the suggested error message and there aren't any downsides as far as I can tell.

**Comment by tersec** [comment]
This was accidentally merged, rather than updated/rebased to current `unstable` -- thus also did revert commit in `unstable`.

**Pull request merged**
