### PR TITLE
Switch to Nim v1.0.0

### PR DESCRIPTION
**Pull request by zah**

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
Legitimate Windows error with "-d:const_preset=minimal":

```text
2019-09-30T02:09:16.0033602Z [NimScript] exec: nim c --out:./build/all_tests -r -d:release -d:chronicles_log_level=ERROR -d:const_preset=minimal --verbosity:0 --hints:off --warnings:off tests/all_tests.nim 
2019-09-30T02:09:40.2810618Z D:\a\1\s\vendor\nimbus-build-system\vendor\Nim\lib\pure\includes\oserr.nim(94) raiseOSError
2019-09-30T02:09:40.2812164Z Error: unhandled exception: The filename, directory name, or volume label syntax is incorrect.
2019-09-30T02:09:40.2812750Z  [OSError]
```

**Comment by arnetheduck** [comment]
that's https://github.com/nim-lang/Nim/issues/12242

1.0.0 is not going to work

also, let's wait for 1.0.2 or .4 before doing this, so that the initial round of bugfixes has gone through

**Comment by Araq** [comment]
> also, let's wait for 1.0.2 or .4 before doing this, so that the initial round of bugfixes has gone through

Yeah, 1.0.2 is scheduled for 8th of October.

**Comment by zah** [comment]
Superseded by https://github.com/status-im/nim-beacon-chain/pull/489

**Pull request closed without merging**
