### PR TITLE
Bugfix: Take into account the finalization delay in the ncli_db rewards calculation

### PR DESCRIPTION
**Pull request by zah**
This fixes a reward calculation error affecting Prater's epoch 31256

### CODE REVIEW

**Comment by arnetheduck** [comment]
this looks like https://github.com/status-im/nimbus-eth2/blob/c7e92bfd842e96f1e9ed1fa997042f9d972bb910/beacon_chain/spec/datatypes/base.nim#L449, no?

**Comment by zah** [comment]
No, this is about whether the whole network is failing to finalize. It's related to the "inactivity leak" mechanism that affects the rewards.

**Comment by arnetheduck** [comment]
> No, this is about whether the whole network is failing to finalize. 

so.. why is the finalized epoch in the state wrong in this case - or rather.. why does it need recomputing?

**Comment by arnetheduck** [comment]
the epoch transition updates the checkpoints before computing the rewards based on the    justification of the previous epoch - if you run this same function on the already-epoch-transitioned state, it will give different results than those that are used in the state transition, no?

**Comment by zah** [comment]
This is a problem with the order of computations (you need a piece of information that is generated by the state transition before you actually run the state transition). You can avoid it by copying the state, but that would slow down the overall processing speed significantly.

**Comment by arnetheduck** [comment]
Yes, but which piece? I'm trying to understand the flow.

**Comment by zah** [comment]
`process_justification_and_finalization` is part of the state transition and it mutates the state by updating the `finalized_checkpoint` field. This field is later read in the formulas affecting the rewards (more specifically in the computation of the `finality_delay` which is replicated here).

Because the current architecture of `ncli_db` is such that we need to be able to collect the reward information before executing the state transition function (the state transition destroys some of the information), we need to compute all the inputs upfront by duplicating the logic in the spec.

**Pull request merged**
