### PR TITLE
bump chronos

### PR DESCRIPTION
**Pull request by arnetheduck**
better error messages on task fail

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
fixes https://github.com/status-im/nimbus-eth2/issues/1118

**Comment by arnetheduck** [comment]
test fail unrelated, macos3 is having issues (cc @jakubgs )

**Comment by jakubgs** [comment]
Where's the error tho?

**Comment by stefantalpalaru** [comment]
`Cannot contact macos-03: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@7a202c2b:macos-03": Remote call on macos-03 failed. The channel is closing down or has closed down` - https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnimbus-eth2%2Fprs/detail/PR-2544/2/pipeline

**Pull request merged**
