### PR TITLE
Spec update in progress; mergeable

### PR DESCRIPTION
**Pull request by tersec**
The idea of this branch is that it can be merged at any time, that after working through the (non-working) https://github.com/status-im/nim-beacon-chain/tree/QuasiGoalState to map out the different changes that need to be made, this can be merged any time, to keep from a single big bang commit.

The spec update has a some just name changes; some minor-ish changes in how it deals with status codes (becomes flags); tends to just query slot numbers for various things to determine penalties; change how committees are represented and processed in a substantial way; tweak how shuffling works; tweak block and epoch processing error condition detection; etc.

The major thing which needs care here is the committee representation, but it seems worthwhile to get the rest available more quickly/incrementally. I'll continue to commit to this branch until it's merged (by me or someone else) then pick up in another new branch.

### CODE REVIEW

**Comment by tersec** [comment]
The CI issue seems Nimble-related. Not looking super-closely at it right now, but the tests apparently run, after Nimble fails. `nimble test` runs locally.

**Comment by zah** [comment]
BTW, do you test that the changes are not triggering problems for the stand-alone simulation that Jacek prepared [1] and the network simulation scripts [2]? I can see that one of the tools used by the network simulation is currently failing to build.

[1]: `nim c -r research/state_sim.nim`)
[2]:  `tests/simulation/start.sh` or `make eth2_network_simulation` in the nimbus repo

**Comment by tersec** [comment]
> BTW, do you test that the changes are not triggering problems for the stand-alone simulation that Jacek prepared [1] and the network simulation scripts [2]? I can see that one of the tools used by the network simulation is currently failing to build.
> 
> [1]: `nim c -r research/state_sim.nim`)
> [2]: `tests/simulation/start.sh` or `make eth2_network_simulation` in the nimbus repo

Oh, that does fail past https://github.com/status-im/nim-beacon-chain/pull/60/commits/cb1096c581865076ba29fbe84538be854ff486d7

So, I'll create another branch which just goes that far, commit those three commits, and keep that and `nimble test` both working.

Still nice to take care of some of the widespread/dispersed renamings in master.

**Comment by tersec** [comment]
https://github.com/status-im/nim-beacon-chain/pull/61/files is the first 3 of these. Will look more closely at the rest of them.

**Comment by tersec** [comment]
@zah it's the
```
  # TODO return error
  doAssert validate_proof_of_possession(
    state, pubkey, proof_of_possession, withdrawal_credentials,
    randao_commitment)
```
in
`process_deposit` in `beaconstate.nim`. This is directly from https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#routine-for-processing-deposits where the assert, which was optional in the code before, is not. It doesn't appear to be related to any of my code here -- switching to your 7608fd76a36fb31c635546556099303db63b3b9f from 5 days ago but forcing that assertion to actually run causes exactly the same result -- and conversely, this branch works fine if that's reverted to how it is in `master`.

So it's not a regression at least.

**Pull request merged**
