### PR TITLE
bump nim-chronicles to fix `BareExcept` warnings

### PR DESCRIPTION
**Pull request by tersec**

### CODE REVIEW

**Comment by tersec** [comment]
Trips up on
```nim
template wrapSideEffects(debug: bool, body: untyped) {.inject.} =
  when debug:
    {.noSideEffect.}:
      when (NimMajor, NimMinor) >= (1, 6):
        {.warning[BareExcept]:off.}
      try: body
      except: discard
      when (NimMajor, NimMinor) >= (1, 6):
        {.warning[BareExcept]:on.}
  else:
    body
```

```
2023-02-24T06:15:18.2506330Z /home/runner/work/nimbus-eth2/nimbus-eth2/vendor/nim-json-rpc/json_rpc/servers/httpserver.nim(31, 62) template/generic instantiation of `async` from here
2023-02-24T06:15:18.2507561Z /home/runner/work/nimbus-eth2/nimbus-eth2/vendor/nim-json-rpc/json_rpc/servers/httpserver.nim(52, 15) template/generic instantiation of `trace` from here
2023-02-24T06:15:18.2508890Z /home/runner/work/nimbus-eth2/nimbus-eth2/vendor/nim-chronicles/chronicles.nim(350, 30) Error: invalid pragma: warning[BareExcept]: off
2023-02-24T06:15:18.2568723Z make: *** [Makefile:420: deposit_contract] Error 1
2023-02-24T06:15:18.2569450Z make: *** Waiting for unfinished jobs....
```

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/issues/4661

**Comment by tersec** [comment]
For the record:
```nim
when (NimMajor, NimMinor) >= (1, 6):
```
should be
```nim
when (NimMajor, NimMinor, NimPatch) >= (1, 6, 11):
```

**Comment by arnetheduck** [comment]
> should be

not all `1.6.11`-versioned versions support `BareExcept` - it was introduced somewhere mid-way

**Comment by tersec** [comment]
Is there a better way of splitting this? Looking for 1.6.12, I guess, but that doesn't exist yet.

**Comment by tersec** [comment]
This version actually re-adds them, e.g.
```
nimbus-eth2/vendor/nim-websock/websock/websock.nim(258, 5) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-websock/websock/websock.nim(256, 34) template/generic instantiation of `futureContinue` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/websock.nim(258, 5) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-websock/websock/websock.nim(256, 34) template/generic instantiation of `futureContinue` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/http/client.nim(42, 76) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/http/server.nim(48, 51) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/http/server.nim(67, 47) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/http/client.nim(42, 76) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/http/server.nim(48, 51) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/http/server.nim(67, 47) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
nimbus-eth2/vendor/nim-websock/websock/websock.nim(258, 5) template/generic instantiation of `async` from here
nimbus-eth2/vendor/nim-websock/websock/websock.nim(256, 34) template/generic instantiation of `futureContinue` from here
nimbus-eth2/vendor/nim-chronos/chronos/asyncfutures2.nim(389, 3) Warning: catch a more precise Exception deriving from CatchableError or Defect. [BareExcept]
```
Probably due to some global affect of its own `BareExcept`-toggling leaking into Chronos.

A better approach there would be not to have to disable/enable it, or use some `push`/`pop` setup. Regardless, this would be counterproductive as-is.

**Pull request closed without merging**
