### PR TITLE
combine ncli_hash_tree_root and ncli_pretty into ncli_ssz

### PR DESCRIPTION
**Pull request by tersec**
The immediate motivation is mainly to reduce CI running times, which have been hitting Azure limits lately. Beyond that, they're virtually the same code, but one prints `hash_tree_root()` and the other prints the pretty JSON output. One line difference, more or less.

ncli_query is just broken anyway:
https://github.com/status-im/nim-beacon-chain/blob/40c2714ff30c811978fcc234f438ddd473851009/ncli/ncli_query.nim#L52-L57

https://github.com/status-im/nim-beacon-chain/issues/364

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
> hitting Azure limits

Every runtime reduction is good, but keep in mind we control those limits: https://github.com/status-im/nim-beacon-chain/blob/1220cc05ad7a8cba8b53801584879537eb5fe75a/azure-pipelines.yml#L4

**Comment by tersec** [comment]
> > hitting Azure limits
> 
> Every runtime reduction is good, but keep in mind we control those limits:
> 
> https://github.com/status-im/nim-beacon-chain/blob/1220cc05ad7a8cba8b53801584879537eb5fe75a/azure-pipelines.yml#L4

Sure, in this case though it's worth doing anyway; I just found it a low priority until it cause CI issues

And, I'd still like to avoid pointlessly long CI runtimes. If it's for good reasons -- running more tests, for example -- that's fine, but it's silly to compile more or less the same program twice.

**Comment by arnetheduck** [comment]
fwiw, the ncli suite of tools were really meant to be a single sub-command style tool but there were issues with the CLI library selection at the time so they ended up like this for pragmatic reasons - the more that end up under the same roof, the better probably (ie `ncli pretty` vs `ncli_pretty` - the former seems better)

**Comment by arnetheduck** [comment]
as such, we could also call it `ncli` simply..

**Comment by tersec** [comment]
> as such, we could also call it `ncli` simply..

I'm okay with that, but I kept this name not aspirational (what we might want in the future), but what it delivers, which is the SSZ-themed parts of a theoretical `ncli` tool in one binary. As they continue to merge, there's no reason to keep calling it `ncli_ssz`.

Or, I'm fine with renaming it now, but it seems arguably premature given that we still have `ncli_db`, `ncli_transition`, etc.

**Comment by tersec** [comment]
Azure 32-bit ran for 1h7m successfully. Azure 64-bit timed out just before it was able to finish `state_sim` and start `block_sim`. This PR still improves things -- it doesn't affect the `make test` part of CI at all, and with the same Azure virtual host speed, it got farther than it would have. But it does illustrate the motivation.

**Comment by arnetheduck** [comment]
wanna throw transition in there as well? `db` should probably be separate since it goes full-blown database + blockpool, whereas the others are `spec`-only

**Pull request merged**
