### PR TITLE
use libbacktrace on Windows

### PR DESCRIPTION
**Pull request by stefantalpalaru**

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
And we have a new record for the fastest overall CI run: 35m 45s - https://github.com/status-im/nimbus-eth2/actions.html?page=1&workflow_file_name=ci.yml

**Comment by cheatfate** [comment]
I would not recommend to merge this PR. I had a lot of crashes on Windows with `nim-libbacktrace` enabled. And i haven't see any crashes while it was disabled.

**Comment by stefantalpalaru** [comment]
The libunwind bug you were affected by was fixed upstream: https://github.com/llvm/llvm-project/commit/542db87f1ac67087aeb5cf572b1f9744d482da69

**Comment by zah** [comment]
How can we merge this in a responsible way? It looks like we'll need macOS and Windows nodes on the fleet to subject to the appropriate level of testing.

**Comment by stefantalpalaru** [comment]
It works in CI and there's a way to opt out by passing USE_LIBBACKTRACE=0 to Make.
No extraordinary testing needed.

**Comment by cheatfate** [comment]
> 
> 
> The libunwind bug you were affected by was fixed upstream: [llvm/llvm-project@542db87](https://github.com/llvm/llvm-project/commit/542db87f1ac67087aeb5cf572b1f9744d482da69)

LOL, you didn't believe that it was `libbacktrace/libunwind` bug, you was saying it was our hidden bug inside of our code, and it was impossible to convince you otherwise...

**Comment by stefantalpalaru** [comment]
Even I am wrong, sometimes :-)

**Comment by stefantalpalaru** [comment]
Superseded by https://github.com/status-im/nimbus-eth2/pull/3466

**Pull request closed without merging**
