### PR TITLE
Revert "fixes"

### PR DESCRIPTION
**Pull request by tersec**
Reverts status-im/nimbus-eth2#2901

don't merge, for now

Check for if it's breakage cause

### CODE REVIEW

**Comment by arnetheduck** [comment]
fwiw, the linux tests finalized, so this looks like an unlikely candidate (there are no material changes in it - the rest deserialization affects only beaconstate which is never sent across the wire in  the fin test

**Comment by tersec** [comment]
Not for https://github.com/status-im/nimbus-eth2/commit/e47a8cbe4242a37e01b402ce5d77853394c6971e -- both Jenkins platforms failed.

**Comment by tersec** [comment]
I want to avoid post hoc ergo propter hoc here though; e.g., Jenkins hosts sometimes fail for a while for other reasons, and some commit's the last working one/first non-working-looking one.

Watching Jenkins runs from https://github.com/status-im/nimbus-eth2/commit/5bfff4378574f6fc84e5508607c17b0a38160d28 and if they're fine, then it was very likely just a glitch. Also rebased https://github.com/status-im/nimbus-eth2/pull/2890 to resolve conflicts, so watching that for similar reasons.

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/commit/5bfff4378574f6fc84e5508607c17b0a38160d28 is fine, so probably it's just a glitch.

**Pull request closed without merging**
