### PR TITLE
Remaining work on state_transition

### PR DESCRIPTION
**Pull request by JGcarv**
Hello!

This PR addresses the remaining work on #762 , adding a signature verification on `state_transition`.

The code will need to change once #780 is merged, both to address the new api for signing(and verifying) as well for incorporating the Domain type in `helpers`, so I'm not sure if it's worth merging as is. 

Let me know what you think!
Thanks,
JG

### CODE REVIEW

**Comment by zah** [comment]
Thank you, Joao, I think we can merge this now and deal with the rebase of #780 afterwards (it already has a number of conflicts that need to be addressed).

**Comment by arnetheduck** [comment]
Perfect! This branch makes it easier to deal with all BLS related things in one branch - let's leave the ticket open as well until we have clarity on the test case - protolambda has indicated zcli will be upgraded "soon" to 0.10 so we can easily wait for that (or check with some other client like lighthouse - it would likely require breaking their bls sig check on purpose and running the test.

**Comment by tersec** [comment]
This breaks `make eth2_network_simulation` for me, either with the daemon or libp2p native reliably -- every time I've run commit f29bfef5a7e4a81130e232b438ec2ebccaa4b664 from the `devel` branch it's been fine, and this hasn't worked for me once.

Whether that's due to exposing some underlying bug, introducing an additional bug, being some quirk of my own setup, or some other combination of possibilities, would be one reasonable next question.

**Comment by tersec** [comment]
We agreed in Discord chat to pull this out of `devel` for the time being, pending further investigation of why it's not finalizing. It's probably close to doing so, but that work shoudl be done while it's still in a branch.

**Comment by tersec** [comment]
@JGcarv further development will continue in https://github.com/status-im/nim-beacon-chain/pull/797

**Comment by JGcarv** [comment]
I'm sorry for the trouble!

I didn't realize that this testing suite even existed, so I thought it was all good. I'll do some investigation to see if I can find the issue.

**Comment by tersec** [comment]
This was great, actually -- it demonstrated a hole in the testing, so, thank you for that.

The trouble was on our end -- until just an hour or two ago, that test suite wasn't run automatically as it should have been. It wasn't sufficiently documented that this was important or even existed. That responsibility for documenting and setting up that infrastructure so that the the easiest thing to do was the correct thing to do was on us, to enable people to most efficiently and with fewest surprises contribute.

I, at least, and presumably the other people on the Nimbus team, welcome your further contributions, to this and any other issues you find interesting or worthwhile.

**Comment by stefantalpalaru** [comment]
That script creates logs for each node in the "local_testnet_data" directory. To raise the log level:

```text
./scripts/launch_local_testnet.sh --testnet 0 --nodes 4 --log-level TRACE --disable-htop -- --verify-finalization --stop-at-epoch=5
```

Only Linux is supported, because we run the testnet only on Linux hosts, for now.

**Pull request merged**
