### PR TITLE
add CI check for options documentation

### PR DESCRIPTION
**Pull request by etan-status**
Ensure that documented options reflect available beacon node options.

### CODE REVIEW

**Comment by etan-status** [comment]
Requires https://github.com/nim-lang/Nim/pull/21643

**Comment by etan-status** [comment]
Weird, for some reason it works in Jenkins. On my local machine, can confirm `COLUMNS` to be ignored when running directly from Terminal.

**Comment by etan-status** [comment]
I guess all the methods beside `COLUMNS` probably fail if there is no interactive terminal attached, hence COLUMNS working on jenkins. anyhow, @tersec no need to wait for the Nim fix for this PR.

**Comment by etan-status** [comment]
You can see how it looks in case it detects inconsistencies, if you click to the previous build in Jenkins (that didn't use the COLUMNS override)

**Review by tersec — APPROVED** [review]

**Pull request merged**
