### PR TITLE
chore: fix some comments

### PR DESCRIPTION
**Pull request by renshuncui**

### CODE REVIEW

**Comment by tersec** [comment]
Needs to target the `unstable` branch

**Comment by renshuncui** [comment]
> Needs to target the `unstable` branch

Thanks.  Modified

**Comment by tersec** [comment]
One of the files you modified also therefore needs a copyright year update, which is otherwise causing the linting CI check to fail:
```
Run excluded_files="config.yaml"
The following files do not have an up-to-date copyright year:
- scripts/signers/web3signer.sh
Error: Process completed with exit code 2.
```

https://github.com/status-im/nimbus-eth2/blob/fd4398d4c5ab5583059f877b6f96cb70d8026aa9/scripts/signers/web3signer.sh#L3
should read
```sh
# Copyright (c) 2023-2024 Status Research & Development GmbH.
```

**Comment by tersec** [comment]
Thank you for your comment fixes; they've been incorporated into `unstable`.

**Pull request closed without merging**
