### PR TITLE
Prefer converting int` to uint64 and switch foo.len.uint64 to .len64

### PR DESCRIPTION
**Pull request by tersec**
- removed some pointless type conversions by better coordinating choice of which integer type's used across function call boundaries, or between loop init values/bounding values;

- where it made sense (and where found; used an asserting template to trip up `uint64` to `int` conversions, but some were obviously harmless and any change would have been pointless churn), preferred treating `int` as the internally-generated values they are, typically from `len` or `for` loops, ensuring they're converted to `uint64` rather than vice versa. Fuzzing has already found a couple of case where the other way around created underflow which hadn't been tested for; and

- to keep this style more idiomatic/preferred and to centralize the remaining type conversions, encapsulated the common `.len.uint64`, of which 29 instances were switched, to `.len64`, so the more-or-less unavoidable-so-far type conversion at least isn't diffusely distributed through the codebase, in that specific situation where it is, indeed, safe.

https://github.com/status-im/nim-beacon-chain/pull/1375/commits/c821ebd77d91e8b5c891b1c4b6d77da671fa7939 fixing `state_sim` on 32-bit Azure suggests a Nim bug:
```
          mapIt(
-           0'u64 ..< committees_per_slot,
+           0 ..< committees_per_slot.int,
```
It's a non-issue on 64-bit platforms in CI.

The other loops/`mapIt`s changed are

- in `tests/test_state_transition.nim` and ` tests/mocking/mock_deposits.nim`, which, if the test suite passes, it's fine;

- `is_valid_merkle_branch()`, but it doesn't change the loop index/bounds types, just that it doesn't convert in the function itself;

- ` nfuzz/libnfuzz.nim`, which should show up soon if it doesn't work and doesn't affect the testnet correctness or CI functionality either way.

### CODE REVIEW

**Comment by arnetheduck** [comment]
shall we call it `lenu64`?

**Comment by arnetheduck** [comment]
@zah I'd be guessing that what this branch finds in terms of azure is what prevents ssz from working on 32 bit as well - this is a pretty serious nim bug, if so

**Comment by tersec** [comment]
> shall we call it `lenu64`?

https://github.com/status-im/nim-beacon-chain/pull/1375/commits/be377ec6f0bd751de8ca0d2bea831086095baf28

**Comment by zah** [comment]
@arnetheduck, have we found a minimal test case the 32-bit issue btw? Was it reported upstream?

**Comment by arnetheduck** [comment]
not that I know, though our nbc test suite shows it (on 32-bit raspi for example)

**Comment by tersec** [comment]
The case here specifically was for a loop from `0'u64 .. 0'64`, i.e. one iteration total, and it was trying to access index 1, which suggests it ran off the end of the loop/didn't terminate properly.

There's one committee per slot at the state sim at the validator numbers used (3000 < 4096), and that loop iterates over the committees per slot.

**Comment by tersec** [comment]
Looks like this exact situation (`uint64` iteration from `0'u64` to `0'u64`) is what @zah documented in https://github.com/nim-lang/Nim/issues/14616 which has since been fixed.

**Pull request merged**
