### PR TITLE
RFC: remove phase0 and altair REST JSON block deserialization

### PR DESCRIPTION
**Pull request by tersec**
Keeps writing, because that's required for the REST server to serve historical blocks.

### CODE REVIEW

**Comment by etan-status** [comment]
What about a client reading archive data?

**Comment by tersec** [comment]
> What about a client reading archive data?

Existing databases, i.e. local archives to a particular BN, are untouched by this. This is strictly a set of changes to the REST reading support.

Furthermore, because the REST server with these changes can still write phase0 and altair blocks in response to queries, clients looking for archive data from a BN can still get it.

**Comment by tersec** [comment]
In general, the purpose of the reading support in the REST server and validator client was/is to create new blocks, but there's been no need to create new phase0 or altair blocks in years.

**Comment by arnetheduck** [comment]
Using eth2 as a library to consume data is also impacted (like a UI showing blocks, like the GUI I maintain) - the cost is low to non-existent, I don't see the point of actively removing this.

**Comment by tersec** [comment]
Alright. Worth at least making this an explicit/intentional decision.

**Pull request closed without merging**
