### PR TITLE
remove `newPayload` from block production flow

### PR DESCRIPTION
**Pull request by tersec**
https://github.com/status-im/nimbus-eth2/issues/4181#issuecomment-1258568058 has more context.

Upshot is that at this point it's a safeguard which probably costs more than is worth.

This specifically requires testing in situations which trigger multiple consecutive block proposals by the same node.

### CODE REVIEW

**Review by arnetheduck — APPROVED** [review]

**Comment by arnetheduck** [comment]
So this still needs the update to `BlockProcessor`?

**Comment by tersec** [comment]
> So this still needs the update to `BlockProcessor`?

Yes, and that couldn't happen (sans rebasing/merge conflicts) until https://github.com/status-im/nimbus-eth2/pull/4192 was merged, because it modifies that part of `BlockProcessor` too, so the rebasing here to `unstable` was to pull that in pre-emptively.

**Comment by tersec** [comment]
It would also be preferable to merge https://github.com/status-im/nimbus-eth2/pull/4182 before adding `BlockProcessor` changes to this -- it's cleanly mergeable at the moment, but it becomes messy if it waits, since it's going to affect the whole module.

https://github.com/status-im/nimbus-eth2/pull/4182/files#diff-a09c99ea4dc7b4118405b5b5c2985124f3ac10247f3d69c9611c22ca7c496f48

**Comment by tersec** [comment]
> So this still needs the update to `BlockProcessor`?

https://github.com/status-im/nimbus-eth2/pull/4186/commits/03aba9dddff1e48a815cd936c85fbbb0f31132ca

This has some tradeoffs, but I'm not sure they're avoidable:
- it means `processBlock` and `storeBlock` in `block_processor` are async. In theory, this shouldn't matter until it reaches the first yield point, in terms of compounding scheduling latency upon scheduling latency, but that wasn't even a possibility before;

- it relies slightly more on the guarantee that `BlockProcessor` will be a singleton than before, because as a result of this `async` transformation, it can't use `var BlockProcessor` but rather `ref BlockProcessor`. In theory harmless, in practice a slightly increased risk;

- somewhat more avoidable, but more a case of it not making sense to return to outer layers of callers in the REST and `validator_duties` layers which have no good mechanism for this block rescheduling that `block_processor` can do, it complicates the `BlockError`-based `storeBlock` return type somewhat to signal the whether to continue to effectively loop on that block. This should at least replicate existing semantics: loop on the block in a similar way, and, albeit differently (before, `validator_duties` detected `newPayload` failures more directly, treat failure of that first `newPayload` as an error. There's probably not time to try again, in terms of retries, because that first `newPayload` can already take up to 8 seconds per specification to time out. If it hasn't worked by then, `validator_duties` needs to move on regardless; and

- as a more philosophical difference, it takes the `storeBlock` notion more seriously than before of validating, always, without the fast path it used to have of being able to specify from the outside to `storeBlock` that the EL block/execution payload was presumed `VALID`. This is arguably more correct, but depends on one's views of how much to the REST API is supposed to be able to provide arbitrary input, and also increases the baseline latency of `storeBlock`.

It's probably an overall net improvement, but definitely comes with its ugliness. Because this `newPayload` still happens within `storeBlock`, `storeBlock` time as a whole won't decrease, and might increase, but the actual block broadcast does happen first regardless.

**Pull request merged**
